### ISSUE TITLE
[feature] Embed jadx as a library

### ISSUE THREAD

**Issue by myzhan** [skylot/jadx#1006]
*Describe your idea:*

I'm tring to embed jadx into my project and use it as a library. But when I import it from jitpack, it seems that some dependencies are missing.

https://jitpack.io/p/skylot/jadx

**Comment by skylot** [comment]
Sorry, I never set up jitpack build, so it is unofficial and not supported. Also, I don't know how to disable it :disappointed: 

Anyway, I understand that some people want to use jadx as a library, so I will try to make official maven artefacts.
But, to be honest, I am not happy with current jadx API and I plan to make breaking improvements. And because of this jadx still don't have an easy way to be used as a library.

**Comment by myzhan** [comment]
In fact, after manually adding android-29-clst.jar, android-29-res.jar and dx-1.16.jar to CLASSPATH, I'm able to use jadx as a library. But it's hard to publish my project to maven with these external jars.

It will be cool if jadx is published to maven with these dependencies.

**Comment by Dordy175** [comment]
> Sorry, I never set up jitpack build, so it is unofficial and not supported. Also, I don't know how to disable it 😞
> 
> Anyway, I understand that some people want to use jadx as a library, so I will try to make official maven artefacts.
> But, to be honest, I am not happy with current jadx API and I plan to make breaking improvements. And because of this jadx still don't have an easy way to be used as a library.

It would be really nice 👍  We need that @skylot 🥇

**Comment by myzhan** [comment]
@Dordy175 I can use it as a library, but I'm also waiting for an official solution, so I can simply add it as a normal maven dependency.

**Comment by ThexXTURBOXx** [comment]
> Sorry, I never set up jitpack build, so it is unofficial and not supported. Also, I don't know how to disable it 😞

@iBotPeaches has set up a simple `.jitpack.yml` file which disables jitpack completely (intentionally):
https://github.com/iBotPeaches/Apktool/blob/master/.jitpack.yml

> Anyway, I understand that some people want to use jadx as a library, so I will try to make official maven artefacts.

That sounds really nice. I am looking forward to that as well! Is there some planned release date already? :)

> But, to be honest, I am not happy with current jadx API and I plan to make breaking improvements. And because of this jadx still don't have an easy way to be used as a library.

Actually, [bytecode-viewer](https://github.com/Konloch/bytecode-viewer) already uses JADX as a [decompiler](https://github.com/Konloch/bytecode-viewer/blob/master/src/main/java/the/bytecode/club/bytecodeviewer/decompilers/impl/JADXDecompiler.java) and I think that the API is not that bad to use.
But if you plan to do breaking changes, I of course understand that an official release of the library might only make sense after some thinking-through of stuff.

**Comment by skylot** [comment]
> a simple .jitpack.yml file which disables jitpack completely (intentionally):

Nice! Thanks for the tip @ThexXTURBOXx! But for now, until I set up an official maven repo, I think it is ok that people can use jitpack, because it is better than nothing :)

> Is there some planned release date already?

Sorry not yet. But I think I will make it in next release with a current state of API. As you mention, it is fine, and I also resolve issues from above (remove android-*.jar and almost get rid of dx lib dependency).
Main reason I don't like current API is that it allows only simple decompilation (just to get code strings), but some people want to get more info, change something inside or even use a scripting language (#1175). It is possible only using jadx internal API which is very unstable, and I am not sure that I can make it stable :(

**Comment by skylot** [comment]
Jadx artifacts now available in maven central repository ([list](https://search.maven.org/search?q=g:io.github.skylot%20AND%20a:jadx*)), check [wiki page](https://github.com/skylot/jadx/wiki/Use-jadx-as-a-library) for details.

**Comment by am009** [comment]
Sorry for replying to this old thread.

[Here](https://github.com/am009/hello-jadx) (https://github.com/am009/hello-jadx) is my simple "hello world" maven project that used Jadx as a library, which is a good starting point if someone wants to use Jadx as a library.

I hope it is useful for anyone who comes across this page.
