### ISSUE TITLE
[core] Don't suppress output for methods with many nop instructions

### ISSUE THREAD

**Issue by yawkat** [skylot/jadx#1038]
Jadx outputs fallback instructions when decompilation fails. In https://github.com/skylot/jadx/blob/master/jadx-core/src/main/java/jadx/core/codegen/MethodGen.java#L293-L296 , this output is suppressed for methods that contain more than 100 instructions. While this sounds like a good idea, it also hits some methods that are mostly comprised of `nop` instructions, which are skipped in the output anyway.

The easiest solution is replacing the check with `Stream.of(insnArr).filter(insn -> insn != null && insn.getType() != InsnType.NOP).count() > 100`, though there are also solutions that are more efficient. I'm not sure if this code path is hot enough to justify using a more efficient approach.

If this change sounds like a good idea I can build a PR for it.

**Comment by skylot** [comment]
@yawkat sure, this looks like a nice improvement. Performance is not a high priority here, because fallback not used very often, so your solution is good enough.
By the way, for small changes, you can directly open PR. I add issue requirements mostly for big change coordination (to prevent merge conflicts) and also to help choose a good start point and architecture hints.

**Comment by yawkat** [comment]
Yea, just didn't want to build a test case before knowing a fix would make sense. Submitted.
