### ISSUE TITLE
[core] Unable to decompile anything

### ISSUE THREAD

**Issue by MrAdityaAlok** [skylot/jadx#1075]
**Describe error**
I just installed jadx latest version and on running `jadx --version`  it shows following error
- full name of method or class with error
```
Exception in thread "main" java.lang.BootstrapMethodError: Exception from call site #40 bootstrap method
        at jadx.core.utils.files.FileUtils.deleteDir(FileUtils.java:97)
        at jadx.core.utils.files.FileUtils.deleteTempRootDir(FileUtils.java:124)
        at jadx.cli.JadxCLI.main(JadxCLI.java:26)
Caused by: java.lang.ClassCastException: Bootstrap method returned null
        ... 3 more
```

[App.zip](https://github.com/skylot/jadx/files/5759078/App.zip)

**Comment by skylot** [comment]
@MrAdityaAlok can you share your Java version? (`java -version`). If possible try the latest java version.

**Comment by MrAdityaAlok** [comment]
I am using OpenJDK15U-jdk_aarch64_linux_hotspot_15.0.1_9 by AdoptJDK

**Comment by jpstotz** [comment]
@MrAdityaAlok As your OS is Linux on ARM, you are trying to run Jadx on a Raspberry? Please post your system hardware spec plus OS name and version.

**Comment by MrAdityaAlok** [comment]
>  Please post your system hardware spec plus OS name and version.
   - OS: Android 9
   - Host: LENOVO Lenovo TB-X605LC
   -  Kernel: 4.9.11
   -   Shell: zsh 5.8
   - Terminal: termux
   - Chipset: msm8953
     - CPU: Qualcomm Technologies

> @MrAdityaAlok As your OS is Linux on ARM, you are trying to run Jadx on a Raspberry?

No I am using Android.

**Comment by jpstotz** [comment]
That is really a special run-time environment. Are you sure you only have installed the mentioned AdoptOpenJDK version? Do you use a pre-compiled version of jadx or have you compiled it in that environment? Because the error shown in your first post usually occurs if you mix-up different Java versions.

**Comment by alissonlauffer** [comment]
Interestingly I got the same issue in my device with Android 11 after converting all JADX jars with `dx` and trying to execute it with the `dalvikvm` command.

**Comment by MrAdityaAlok** [comment]
> Edit: I just made q quick test, but based on my experience the mentioned Java version does not run on Termux because of libc issues. Therefore if you have a special environment please describe the the full way how to achieve it. Just downloading Java does definitely not work.

I used JDK under proot of ubuntu 20.04 and as mentioned by @alissonlauffer first used dex on the jars.

I am new to Android as well as JAVA please mention if I did something wrong.....

**Comment by jpstotz** [comment]
If you are trying to run a dexified version of Jadx why have you then answered you are running Jadx using  OpenJDK15U-jdk_aarch64_linux_hotspot_15.0.1_9 in your second comment?

From my perspective Android/dalvikvm is not an environment targeted by Jadx. Jadx was developed for Java 1.8+ using a regular J2SE JVM. The differences are too big between J2SE and Android so that I don't see a way to add support for such an environment - sorry.

Therefore I would recommend to you to try to get a real J2SE JVM running on Android if you really want to run jadx on Android. But the recommended way if to run Jadx on a regular PC that runs Linux/Windows/MacOS.

**Comment by MrAdityaAlok** [comment]
Okay ....and sorry for wasting your precious time 🥺..... please... sorry

**Comment by danieldjewell** [comment]
@Mr-Elliot-Alderson Check out https://github.com/TermuxArch/TermuxArch for running Arch inside of a proot inside of Termux. JRE/JDK 8 is available on there and it usually works...

Another thing: Termux is awesome but because it's running in an Android app, many things built for "Linux" (especially pre-built packages) won't work. I just looked up the AdoptOpenJDK site -- looks like their pre-built binaries are linked against glibc. Android doesn't use glibc: it uses bionic (https://github.com/aosp-mirror/platform_bionic) ... (I believe TermuxArch gives you glibc .... among other things.) Bionic doesn't support 100% of glibc features (e.g. no semaphores -- if you see compilation errors about sem_open or semaphores....) -- and that's often why the packages for termux (https://github.com/termux/termux-packages have lots of patches to get them to work properly...
