### ISSUE TITLE
[bug] Issue with line numbers on line wrap

### ISSUE THREAD

**Issue by green9317** [skylot/jadx#1092]
There is a minor bug in PR #1090 with the way that line numbers get displayed when activating line wrap.  When a line is to long and needs to be wrapped the line that is created gets a new line number and all of the code gets shifted down one.  However if there is a gap in line numbering due to a comment the line numbers for lower sections of code don't get shifted causing the numbers to be in the incorrect location.

I would also request when a line needs to be wrapped don't number the new line created as it is technically part of the line above it.

Overall, I am really happy with the changes made especially the ability to do line wrapping.

![jadx_line_number_issue](https://user-images.githubusercontent.com/38409554/105616486-5f875f80-5d7b-11eb-9a78-05411a052747.gif)

**Comment by jpstotz** [comment]
The line numbers have to change not only when the "Line Wrap" feature is enabled/disabled but also when the code view is resized and therefore lines suddenly are broken down or reassembled. 

Detecting if a line is an "original line" or a line created by a dynamic line wrap seems to be pretty complicated in JTextArea (and therefore also for our RSyntaxTextArea/CodeArea).
Based on a [line number painter example I found](http://www.camick.com/java/source/TextLineNumber.java) that claims to work with line wrappings you have to calculate the begin and ending of each line (instead of simple enumerate all line as it is currently done in `LineNumbers.paintComponent(..)`.
Instead you have to use the text offset and loop through the results of `rowStartOffset = Utilities.getRowEnd(component, rowStartOffset) + 1;`.

**Comment by skylot** [comment]
@jpstotz I think I can fix this. I just need to do the same as in the official `LineNumberList` component [here](https://github.com/bobbylight/RSyntaxTextArea/blob/8173094d4ec0b520d8603269feb8fb8a7c6c0c4a/RSyntaxTextArea/src/main/java/org/fife/ui/rtextarea/LineNumberList.java#L408). Previously I just skipped support for line wrap, sorry :disappointed:

**Comment by skylot** [comment]
Fixed. Can anyone check? Just to be sure :smile:

**Comment by jpstotz** [comment]
@skylot Your patch seems to work properly thanks.
