### ISSUE TITLE
my test failed, help me please...

### ISSUE THREAD

**Issue by LBJ-the-GOAT** [skylot/jadx#1096]
hi, I am trying to add a rename variable feature, it works well on gui, but when I trying to build it for committing a PR, I got this error on my console... I tried but can't fix it, would you please help me @skylot,  thank you.   [code's here](https://github.com/skylot/jadx/commit/d84a13285c3d11c0b31b4d5ad72aa92499133348)

```
jadx\jadx-samples\build\samples-jadx\src\sources\jadx\samples\RunTests.java:76: error: variable th is already defined in method runTest(String)
        String th;
```

**Comment by skylot** [comment]
Well, you break variable naming, so code looks like this:
```java
    private static boolean runTest(String str) {
        Throwable th;
        String th;
        boolean th;
```
Not sure which change exactly break this because you made lots of changes in code generation.
Also looks like you override variable names from debug info.

To spot such issues you can run any junit test from core module, [TestArrayForEach](https://github.com/skylot/jadx/blob/c7890f2468a14147d80b151dcac17a7875648fea/jadx-core/src/test/java/jadx/tests/integration/loops/TestArrayForEach.java#L25) for example.

**Comment by LBJ-the-GOAT** [comment]
> Well, you break variable naming, so code looks like this:
> 
> ```java
>     private static boolean runTest(String str) {
>         Throwable th;
>         String th;
>         boolean th;
> ```
> 
> Not sure which change exactly break this because you made lots of changes in code generation.
> Also looks like you override variable names from debug info.
> 
> To spot such issues you can run any junit test from core module, [TestArrayForEach](https://github.com/skylot/jadx/blob/c7890f2468a14147d80b151dcac17a7875648fea/jadx-core/src/test/java/jadx/tests/integration/loops/TestArrayForEach.java#L25) for example.


Okay, I get it, thanks.
