### ISSUE TITLE
[feature] please add support ida's idc script

### ISSUE THREAD

**Issue by ohyeah521** [skylot/jadx#1172]
*Describe your idea:*
In the reverse analysis, it is necessary to quickly locate the feature codes of different versions of the same software according to the feature codes, so the binary fuzzy display is required, similar to ida's find_binary

example：
addr1 = find_binary(0, SEARCH_DOWN, "22 ?? 31 ?? ?? ?? 51 ?? ?? ?? 15 ?? ?? ?? 38 ?? ???? ?? ?? 39 ?? ?? ??");

**Comment by skylot** [comment]
@jpstotz for me main question is: What features people expect from scripting in jadx?
I can think of exposing api to write jadx visitor passes, which allows transforming and modification of generated code. This can be useful for custom deobfuscation, code simplification, etc.

> what scripting language to use

This can be a plain Java, because I already use it in test to compile generated code and invoke methods ([see here](https://github.com/skylot/jadx/blob/50cfa4c9716dc94535714331bacf7ca110abfba3/jadx-core/src/test/java/jadx/tests/api/compiler/DynamicCompiler.java#L34))
Or it can be a [Kotlin script](https://github.com/Kotlin/KEEP/blob/master/proposals/scripting-support.md) which is nice and close for Java :)

> Besides the scripting language Jadx would require some stable API for that scripting language. 

We will need some kind of wrapper for scripting, so this wrapper can be our API.


Anyway, scripting support in jadx is a big task, and I am not sure that it will be used by many users. And as always I think that decompilation quality is more important for users, so it will be always top priority.
Maybe I will open separate issue for discusision scripting support in jadx.

**Comment by ohyeah521** [comment]
1. The choice of scripting language doesn't matter. I don't think it is necessary to support too many languages, as long as it supports one and can realize the function.

2. The quality of code decompilation is indeed the most important for users, but the room for improvement is not particularly large. Java's decompilation engine is the bottleneck. I think that in the case of implementing basic functions, you can enrich the functions first, and then attract More developers are involved, there are more people and more power, and finally the decompilation quality of the code is slowly provided

3. From the perspective of virus analysts, scripts can be used to do some automated analysis operations, including but not limited to the following:
 1. Code positioning of sensitive API function calls
 2. Tracking the calling relationship of specific functions or variables
 3. Binary feature code search
 4. Anti-aliasing
 5. Decryption and restoration of encrypted strings

**Comment by ohyeah521** [comment]
> So you are asking for for scripting support in Jadx. I never worked with IDC (I prefer IDAPython).
> Please correct me if I write something wrong: it seems to be a proprietary scripting language that allows to automate actions in the UI
> 
> Implementing something similar for Jadx shouldn't be a big problem. The main question would be what scripting language to use. Unfortunately the Nashorn JavaScript engine has been removed from newer Java versions. Otherwise it would have been a logical choice.
> 
> Other tools also provide scripting languages. For example Ghidra has GhidraScript which seem to be Java language used in a scripting language (not sure if the scripting interpreter is a commonly known library or something proprietary).
> 
> JEB on the other hand seem to integrate Python scripting. Not sure how this is actually implemented. Java and Python typically don't work well together and projects like Jython seem to be stuck on the abandoned Python 2 language.
> 
> When it comes to Java+scripting other languages come to my mind like Groovy. I am not sure which one would be the best choice.
> 
> Besides the scripting language Jadx would require some stable API for that scripting language. Therefore before adding scripting functions to Jadx we may need an interface we can expose to the script. This would be a bit similar to the request to provide Jadx as a library (#1006).

 JEB is the Jython used, so it supports python2.7. The Java language used in the GhidraScript scripting language, but I don't know much about the communication principle between them. Because they are all in the java language, they should be better adapted, so I think it is a better choice to use java as a scripting language

**Comment by skylot** [comment]
@ohyeah521 thank you for your thoughts and suggestions :+1: 
I open a new issue to continue discussion on scripting in jadx #1175.
I don't think I will start work on this right now, but maybe some time in the future. At first, I need to finish and publish stable jadx API, so it will be possible to customize jadx with plugins and next we can make a scripting plugin.
