### ISSUE TITLE
How to fetch the "real" class for some method?

### ISSUE THREAD

**Issue by impvd** [skylot/jadx#1218]
I just decompiled an app with Jadx-gui, and here're the target code that I wanna hook with Xposed:

```java
package androidx.appcompat.widget;

class SuggestionsAdapter extends ResourceCursorAdapter implements View.OnClickListener {
   public Cursor getSearchManagerSuggestions(SearchableInfo searchableInfo, String str, int i) {
  ...
  }
}
```

With the xposed code:

```kotlin
val target = lpparam?.classLoader?.loadClass("androidx.appcompat.widget.SuggestionsAdapter")
        XposedHelpers.findAndHookMethod(target, "getSearchManagerSuggestions", object : XC_MethodHook() {

            override fun afterHookedMethod(param: MethodHookParam?) {
                val cursor = param!!.thisObject as Cursor
                if (cursor.moveToFirst()) {
                    val candidateCnt = cursor.columnCount
                    XposedBridge.log("Loaded app: $candidateCnt")
                }
            }
        })
```

But there's error in log:

```
 EdXposed-Bridge: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.widget.SuggestionsAdapter" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/framework/services.jar", zip file "/system/framework/ethernet-service.jar", zip file "/system/framework/oneplus-services.jar", zip file "/system/framework/oneplus-wifi-service.jar", zip file "/apex/com.android.permission/javalib/service-permission.jar", zip file "/apex/com.android.wifi/javalib/service-wifi.jar", zip file "/apex/com.android.ipsec/javalib/android.net.ipsec.ike.jar"],nativeLibraryDirectories=[/system/lib64, /system/system_ext/lib64, /system/lib64, /system/system_ext/lib64]]
```

It should be something like `com.targetapp.somepath1.somepath2.SuggestionsAdapter`, but I am not sure how to find it.

**Comment by jpstotz** [comment]
When Jadx renames a class then an comment is added containing the original class name. Therefore the class name to hook should be really `androidx.appcompat.widget.SuggestionsAdapter`.

The packageName of the app absolutely nothing to do with the class name. 

Your Xposed code is just a fragment. Have you made sure to only run your Xposed plugin for the app you want to modify? Otherwise it will be executed in other apps as well and if they don't contain the class `androidx.appcompat.widget.SuggestionsAdapter` you will get that error message. 

As I don't see an problem in Jadx addressed in this issue I am closing it. If you have problems developing an Xposed plugin you may better create a question on https://Stackoverflow.com containing the minimum working code of your plugin.

**Comment by impvd** [comment]
@jpstotz Awesome thanks, I just debug it again and logged more details.

```
07-29 22:04:55.002  4529  4529 E EdXposed-Bridge: java.lang.NoSuchMethodError: androidx.appcompat.widget.SuggestionsAdapter#getSearchManagerSuggestions()#exact
```

You are right, the class exists. Just not sure why it said `getSearchManagerSuggestions()` is **NoSuchMethod**
