### ISSUE TITLE
How does jadx-gui convert dex to smali?

### ISSUE THREAD

**Issue by zhangchennan** [skylot/jadx#1227]
I found that jadx-gui can convert dex code to smali. And each java file corresponds to a smali file. However, I found there are no methods in the command-line version of jadx to convert dex to smali for automatic analysis. 
But I found baksmali-2.4.0.jar in the lib. So I try to use baksmali-2.4.0.jar to convert dex files of an apk to smali files. However, the results are different from that of jadx-gui. **There is not a mapping relationship between the smali files from baksmali-2.4.0.jar and java files jadx command line version**. 
So could u please give me some information about how does jadx-gui convert dex to smali?
Thank u very much!!!
- files from jadx-gui
![image](https://user-images.githubusercontent.com/33228682/129031782-d691909b-6847-463d-b3b1-bbbd6c018a74.png)
- java files genrated by jadx command line
![image](https://user-images.githubusercontent.com/33228682/129031924-271f871c-20e9-454e-9049-c7cec9e40855.png)
- smali files genrated by baksmali-2.4.0.jar
![image](https://user-images.githubusercontent.com/33228682/129031670-9e2439d4-8659-40b1-8cbe-d9a4108f4676.png)

**Comment by skylot** [comment]
@zhangchennan did you convert all dex files from apk? Because sometimes classes from same package can be placed in different `classes` files.
> So could u please give me some information about how does jadx-gui convert dex to smali?

You are right, jadx just uses baksmali to show smali files. One difference is that inner classes can be inlined and in jadx you can see several 'smali' classes for one java class. So it is expected that you should have **less** java files than smali files.

**Comment by zhangchennan** [comment]
Thank u very much，I use 
`java -jar baksmali.jar d test.apk -o smalifiles` directly convert an apk to files of smali. I think it will convert all dex files from the apk(i think it supports multidex by default). However, it just converts one dex file to smali. 
So what I need to do now is to integrate these smali files to map to java files generated from jadx command line.
Actually, I have a small suggestion that you can add a function for jadx command line to generate smali files correspond to java files generated by the command line version . It can help to automatic analyze.
Finally, sincerely thank u for ur help!!

**Comment by jpstotz** [comment]
If you want smali files why don't you use `apktool`?

**Comment by skylot** [comment]
> I have a small suggestion that you can add a function for jadx command line to generate smali files correspond to java files generated by the command line version

Well, because after merging several smali files in one (like it implemented now) these files become invalid (smali can't load them), I think it is better to add option for disable inner classes move (inline into base class). After that, java classes and smali files will match.
Also, if you are going to compare java code with smali it is better to disable jadx features that move or rename classes/methods. Suggested options: `--no-inline-anonymous --no-inline-methods --rename-flags "none"`, also don't enable deobfuscation.

**Comment by zhangchennan** [comment]
@skylot  Thanks for ur help!!
