### ISSUE TITLE
Smali decompilation errors

### ISSUE THREAD

**Issue by Elmue** [skylot/jadx#1302]
JADX is by far the best tool that I found so far to analyze APK files.
I tried several others which dont work at all or give less useful results.
It is a high quality project. Thanks for your work.

However I have a problem.
Just the function which I'am interested in has in the body:

```
{
        // Method dump skipped, instructions count: 5131
        throw new UnsupportedOperationException("Method not decompiled:  .......");
}
```
5131 instructions skipped ?
First I would like to understand **why** this happens.

I can get the Smali code from APK Tool and it looks quite reasonable to me.
But reading Smali manually is cumbersome.

My second question is if anything can be done to **fix** this, so that this code can be decompiled to Java.
If it would be partly decompiled with some question maks or comments were problems occur would be better than having 5131 instructions skipped entirely.

And my last question is: If this is not possible is there any **tool** which I can feed with a Smali file and which gives me more human readable output ? All tools which I tried so far here on Github were useless to get this code decompiled.

Here is a link to the Smali file :
https://netcult.ch/elmue/Smali.txt
The function starts at text line 921. It ends at line 8495
It is entirely skipped

And here is the link to the APK file :
https://netcult.ch/elmue/Test.apk.zip

(I had to add a ".ZIP" to the filename otherwise the server will not allow to download the file)

**Comment by tang350476527** [comment]
谢谢您的来信，您的邮件已收到！

**Comment by skylot** [comment]
@Elmue 
At first, you can change `code comments level` option to `debug` it will show method instructions in fallback mode and this method will be very long, so it will be very hard to understand (that's the reason why it is hidden).
Next you can change `show inconsistent code` option to true it will show java code for this method but be careful: this code is incorrect in some way because jadx failed to restore code structure at some point.
For your case: looks like method is very big and uses too much try/catch blocks, so it is hard to restore, sorry 😞 
And as a final solution, you can enable `generate methods cfg graphs` option to dump methods CFG in `.dot` format and next view using any graphviz app.

**Comment by Elmue** [comment]
OK. Thanks for your answer. I will try that. 
But two things I don't understand: 

>  because jadx failed to restore code structure at some point.
Why does it fail at all in restoring the code ?
Isn't it just following a rule to translate Smali into Java ?
What is the problem?

> method is very big and uses too much try/catch blocks

What does "too much" mean?
If there are 1000 Smali try - catch blocks why can this not be translated into a Java code with 1000 try - catch blocks?
Did you set a limit there?
And why?

If there is a huge routine in Smali it is obvious that a huge routine in Java will come out.
But this should not be the problem of JADX.
It is my job then to understand this routine. 
I could copy that to a text editor and remove all code does not interest me and focus and what I want to understand.

But I prefer to have a routine with 1000 try - catch blocks than having nothing.

**Comment by jpstotz** [comment]
> Why does it fail at all in restoring the code ? Isn't this a straight foreward process to translate Smali into Java like what a compiler does? What is the problem?

@Elmue Nothing can be more far away from the truth than this statement. The main problem is that the compiler does not stop after translating Java code to DEX byte code, instead it starts to optimize the code that means it merges duplicate statements if it's complex analysis shows that this has no effect. It moves blocks around and so on so that back tracking which code blocks belong to which if-else or try-catch block (especially when they are nested) can get pretty complicated. Take for example the example I posted in #1262. It is pretty small but complicated to decompile. Now imaging such a problem when it comes to try-catch blocks nested in two or three levels into another.

Additionally DEX code of some apps is modified again after the compiler has finished by code obfuscators. And finally some apps contain DEX code that was never built from Java code. Kotlin and other languages that are directly translated to DEX byte code can generate code that is pretty hard to decompile.

**Comment by skylot** [comment]
@Elmue you can also check [GDA decompiler](https://github.com/charles2gan/GDA-android-reversing-Tool) (it works for your method, using some gotos through) also [JEB](https://www.pnfsoftware.com/jeb/android) can be useful (I didn't check it).
Anyway, I don't think jadx will be fixed for your case soon, also this is a known issue with try/catch, so I will close this issue.

@jpstotz thank you for detailed reply! I always struggle to explain why decompilation is hard, but you did it quite well.
I think I need to state that jadx can't decompile 100% of code in readme, so people will be warned.

**Comment by Elmue** [comment]
Hello

This is already closed. I hope you still read it.

> Take for example the example I posted in #1262. 

OK. I understand the problem.
These 2 if block are impossible to restore into normal Java code.

But have absolutely no problem that incase a code cannot be respoved into the if - else structure that it is simply displayed with goto's inside. This is far better than an error message that 5000 instructions could not be decompiled at all.

**Comment by skylot** [comment]
> simply displayed with goto's inside. This is far better than an error message

@Elmue sure. I plan to implement less verbose fallback option and also working on fixing incorrect CFG with gotos :+1:

**Comment by Elmue** [comment]
And thank you for the hint to try GDA. It is lightnig fast and works very well.
