### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [skylot/jadx#1335]
Hey there!

I belong to an open source security research community, and a member (@haxatron) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by skylot** [comment]
@JamieSlome thank you for a nice report!
I will apply your patch at the next release (approx at January 20).
Also, I have added a [SECURITY.md](https://github.com/skylot/jadx/blob/master/SECURITY.md) as you requested :)

**Comment by JamieSlome** [comment]
@skylot - all the thanks to @Haxatron ❤️ 

Thank you for the incredible speed (wow!), and when you are ready with the fix/next release, be sure to confirm the fix against the report, so that we can go ahead and publish the report + the CVE.

Let me know if you have any further questions, and happy to help! 👋

**Comment by skylot** [comment]
@JamieSlome and @Haxatron I applied patch in release [`1.3.2`](https://github.com/skylot/jadx/releases/tag/v1.3.2) and confirm the fix in the report on huntr.
Thank you for your work!

**Comment by jpstotz** [comment]
@JamieSlome I just checked the provided apk file that contains the AndroidManifest.xml triggering the XXE. I noticed that the xml file is in plain text format instead of binary xml format which is common for Android APK files. Is the plain text format a requirement for the vulnerability or was it just to simplify creation of the test sample? 

Because most APK processing tools do not accept AndroidManifest.xml in plain text format (wonder why Jadx has this capability).

**Comment by Haxatron** [comment]
It was to simplify the creation of the test sample as popular APK packing tools such as apktool did not allow inclusion of external DTDs into the binary XML format of the AndroidManifest file. So I had to manually include it in plaintext.
