### ISSUE TITLE
[bug] saving project error

### ISSUE THREAD

**Issue by zoky2017** [skylot/jadx#1387]
![image](https://user-images.githubusercontent.com/14806642/155275271-3b0b3f7b-18b1-4fca-871f-fdd493ea29ad.png)

**Comment by jpstotz** [comment]
@skylot While testing this bug I noticed that the way JadxGUI handles Exceptions has in my opinion two problems:

1. Exceptions are usually only shown in log file instead of showing an error message
2. When en exception in MainWindow.closeWindow happens Jadx stays and can't be closed at all. 

Regarding 1: What do you think of instead of catching and logging errors in JadxGUI define a general Thread.setDefaultUncaughtExceptionHandler that shows an general (or specific) error message plus may be exception name, message and stack trace and copy everything to clipboard.
 
That would also make it easier for Jadx users to create an issue here on Github (and for us as this would reduce the chance that people post a screen shot instead of a text containing the stack trace.

**Comment by skylot** [comment]
> define a general Thread.setDefaultUncaughtExceptionHandler

@jpstotz sure, that will be very helpful
I'm also thinking about showing error window if error logged from `jadx.gui` package (added in `LogCollector` class). But it can cause many windows to appear at same time if there are several errors has been recorded.
Another way is just popup log viewer window on errors from `jadx.gui` package, so it will behave like error dialog :)

> When en exception in MainWindow.closeWindow happens Jadx stays and can't be closed at all.

Not sure how to handle that, because failing to save project should not be ignored, an error message should appear at least. But at the same time, not closing on request is also bad.
