### ISSUE TITLE
[core]"open" is treated as a keyword

### ISSUE THREAD

**Issue by 3ystem** [skylot/jadx#1394]
When a method name or variable such as "open" appears in the decompiled code, it will be regarded as a java keyword, the look and feel is ambiguous, and it cannot be jumped.
![Snipaste_2022-02-27_14-33-36](https://user-images.githubusercontent.com/38035210/155871265-77c55858-b11b-46e6-aff5-9366e4f6c6f1.png)

**Comment by skylot** [comment]
@3ystem thanks, nice find!
As stated in latest [JSL](https://docs.oracle.com/javase/specs/jls/se17/html/jls-3.html#jls-3.9) `open` is a contextual keyword, so it is become reserved only in modules. But along with others contextual keywords it was added as reserved in RSyntaxTextArea java syntax ([this commit](https://github.com/bobbylight/RSyntaxTextArea/commit/8602e4fe757b2d203ff7d34ef26a6a5962fdc3ca)). I am not expecting this to be fixed in RSTA because it is hard to implement these contextual rules while parsing tokens. So I commit a quick workaround to revert these keywords to identifier. Possible issues (TODOs for the future):
1) for now, jadx don't use these keywords in decompiled code, but this can change at some point (support for java module files for example)
2) performance issues: additional filtering with creation lots of unnecessary string instances
