### ISSUE TITLE
[core] The code generated by "Frida snippet copy action" function is incomplete

### ISSUE THREAD

**Issue by mxy19980428** [skylot/jadx#1396]
When using the "Frida Fragment Copy Action" function of the new version v1.3.3, when I use the function multiple times, there will be "let class = Java.use("classpath");" will not be automatically generated, only the class will be generated Problem with class.method .overload('xxxx') code

**Comment by mxy19980428** [comment]
![截屏-20220228141919-943x318](https://user-images.githubusercontent.com/34773306/155934117-034e4cb0-12a7-4c9d-aa4c-dee17209d25b.png)

**Comment by oriori1703** [comment]
It's on purpose.
I worked on this feature a bit and I also found it weird, but I left it because I figured that's what the original creator of the feature wanted.
I think it would be best to remove this "feature", and if someone doesn't want the class after his first hook, he could just delete that part.

**Comment by mxy19980428** [comment]
Thanks for your answer @oriori1703 , I see, and I also think it should be added that sentence, if someone doesn't want the class after his first hook, he could just delete that part.Because if you delete it after the first use, it is not complete when you want to use it again，would be considered a bug

**Comment by oriori1703** [comment]
I can change that later today if no one else would be than
