### ISSUE TITLE
[bug][gui] New update notification broken

### ISSUE THREAD

**Issue by cskwrd** [skylot/jadx#1397]
I just downloaded the 1.3.3 release. Specifically the [windows jre-free version](https://github.com/skylot/jadx/releases/download/v1.3.3/jadx-gui-1.3.3-1-no-jre-win.exe).

It claims there is a new version available, and clicking it takes me to the release I just downloaded. Might be a string compare issue? The `About` window says my version is `1.3.3-1` and the release is `1.3.3` (no suffix).

**Comment by jpstotz** [comment]
That is because our `VersionComparator` only splits at `.` and not at `-`. In such a case it tries to convert `3-1` to an integer and fails which ends up in a NuberFormatException that is interpreted as "there is an update". 

@skylot I think  it is better not to catch the [NuberFormatExeption](https://github.com/skylot/jadx/blob/master/jadx-gui/src/main/java/jadx/gui/update/VersionComparator.java#L11), just let it pass so it ends up in error log.

**Comment by cskwrd** [comment]
What does the `-1` suffix indicate in this situation? The other available `1.3.3` downloads do not include it. In a similar vein, earlier version of the windows no jre build do not include the suffix. It seems to be introduced with this release.

**Comment by skylot** [comment]
@cskwrd
I commit a fix to handle package version (number after a dash), so this should resolve issue.
I think re-upload of that release file is not really needed because this feature disabled by default now.

@jpstotz thanks! I apply both of your suggestions. And to be honest, I have no idea why I don't use only latest version :(

**Comment by cskwrd** [comment]
Thanks!

**Comment by damm3aa** [comment]
good
