### ISSUE TITLE
[core] jadx run out of RAM quickly (No matter how much) 

### ISSUE THREAD

**Issue by zhongqingsong** [skylot/jadx#1415]
**Checks before report**
- check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki
- search existing issues by exception message
Q&A has wantched, not find the same qustion.So i submit a issue.

**Describe error**
- It's jadx use's memory question. There is a easy way to out of RAM. And it hasn't been optimized, so submit issue to you.
- **Description**：the most easy to show the problem, you drop a apk1 to jadx shorcut, then jadx will work, it's good. After a period of use, you drop a apk2 to the jadx again. Then jadx will close apk1,and begin apk2. So we will find that: the apk1's RAM, it not be cleared(or something else). So the RAM will be double used!!! So the RAM will out use,and soon jadx will be low RAM.
- Let's say apk1 has using 3G RAM, and apk2 is 3G too. It will work very nice when apk single use. But if we drop twice apk, the RAM will use 6G!!! And jadx's RAM will serious lack of!!! And it's not end, we can even drop the apk3, apk4, and so on.
- And ,as we imagine, PC's RAM will lack immediately.But in fact, if when jadx open a new apk, it clear previous apk's useage RAM. This problem will be avoid.

Way to **Reproduction** this issue:
1. drop apk to jadx in multiple (when we open the setting: autode compilation, it will very easy to see)
2. change a setting, and click apply, jadx will reopen apk,as the same as step 1
3. When JADX is not closed, as long as there is the act of opening APK multiple times,the RAM will use strongly.

- **IMPORTANT!** attach or provide link to apk file (double check apk version)
- Any apk can reproduction

  **Note**: GitHub don't allow attach files with `.apk` extension, but you can change extension by adding `.zip` at the end :)

**Comment by skylot** [comment]
@zhongqingsong thanks for report. Actually I know about this issue and tried to fix it several times, the latest try was in commit c4e1d9445ab7e55e9e64d46edcb2cfc2f7936396, so it is worth checking the latest release.
Anyway, I will recheck again and will try harder to fix this issue :+1:

**Comment by jpstotz** [comment]
Are you referring to the memory usage shown by Jadx itself in the memory usage bar or the actual RAM usage e.g. shown by a system tool like task manager?

If it is the latter what Java version do you use, on what OS and how do you start Jadx? Because Java has it's own memory management system and only the newer java versions in combination with certain garbage collectors are able to pass back unused memory back to the OS. So if you are using the wrong garbage collector Jadx is not able to free memory in way that it is returned to the OS.

**Comment by zhongqingsong** [comment]
> Are you referring to the memory usage shown by Jadx itself in the memory usage bar or the actual RAM usage e.g. shown by a system tool like task manager?
> 
> If it is the latter what Java version do you use, on what OS and how do you start Jadx? Because Java has it's own memory management system and only the newer java versions in combination with certain garbage collectors are able to pass back unused memory back to the OS. So if you are using the wrong garbage collector Jadx is not able to free memory in way that it is returned to the OS.

Sorry, I use the newest jadx, seems it worked, RAM will auto clear. It looks fine now.  And yes, i check the RAM use by jadx's UI bar.
And i use java17.

**Comment by zhongqingsong** [comment]
> @zhongqingsong thanks for report. Actually I know about this issue and tried to fix it several times, the latest try was in commit [c4e1d94](https://github.com/skylot/jadx/commit/c4e1d9445ab7e55e9e64d46edcb2cfc2f7936396), so it is worth checking the latest release. Anyway, I will recheck again and will try harder to fix this issue 👍

Thanks. Now one question solved, when drop the other apk, jadx can auto clear RAM. And I tried many times, there is also a small problem that can be optimized.
----
I use the newest jadx,  and drop into some apks into jadx, then I open Win10's TaskManger, find jadx use REAL RAM is 6g. And jadx show 1g total 6g. As I understand it, the 1g is jadx use real RAM, and 6g is the jadx can use max RAM.
And i test another apk: close jadx, and drop a sigle apk into jadx, when jadx ok, bar shows 0.74g / 6.06g. Then check TaskManager, it shows jadx use RAM is 1996mb(2G). This phenomenon is not consistent with my understanding above.
I am not sure which is the question: jadx bar show, or the jadx's RAM is not really cleared out.
So I'm just mentioning it. I'll actually use it later, and if there's a problem, I'll keep giving feedback. 
Thanks anyway.

**Comment by skylot** [comment]
> bar shows 0.74g / 6.06g. Then check TaskManager, it shows jadx use RAM is 1996mb

@zhongqingsong java code runs in java virtual machine (JVM). Shown memory usage is a jadx app usage inside that JVM, and max memory is a hard limit for the app inside JVM (set at startup). But JVM use additional memory for work and often not immediately return freed memory to OS, so actual usage of JVM (you see in task manager) can be much higher than app memory usage inside JVM.
You can click memory usage indicator to force garbage collector and that may reduce memory usage (result highly dependent on current GC used)

> Thanks. Now one question solved, when drop the other apk, jadx can auto clear RAM

Looks like this issue is resolved, so I will close it. If you still have any questions, feel free to ask.
