### ISSUE TITLE
[core] Class renamed with disabled deobfuscation

### ISSUE THREAD

**Issue by zhongqingsong** [skylot/jadx#1419]
**Checks before report**
- the new jadx problems arising, the old jadx none of these problems.

**Describe error**
- Real name is com.yandex.metrica.impl.ob.pu, and jadx show the name is com.yandex.metrica.impl.ob.C1994pu.
Jadx show a few extra letters. And i did't open de-obfuscate. Below is my settings.
And there is also other wrong class name like:
com.yandex.metrica.impl.ob.AbstractC2234xn   = real class is com.yandex.metrica.impl.ob.zk
com.yandex.metrica.impl.ob.AbstractC2227xg   = real class is com.yandex.metrica.impl.ob.xg
com.yandex.metrica.impl.ob.C1726hD               = real class is com.yandex.metrica.impl.ob.hD
And so on, many class names have been changed.
- Question two: there is a language it show wrong.

![image](https://user-images.githubusercontent.com/35858818/159612257-805e45f0-cb42-4985-a48c-9e357b24949e.png)

- **IMPORTANT!** attach or provide link to apk file (double check apk version)
https://cdn-us01.apkcombo.com/com.yd.dinorunner/%E6%81%90%E9%BE%99%E5%BF%AB%E8%B7%913D%E2%80%94%E7%96%BE%E9%80%9F%E5%86%B2%E6%92%9E_2.3.83_apkcombo.com.apk?ecp=Y29tLnlkLmRpbm9ydW5uZXIvMi4zLjgzLzgzLmM1NjljMTJlNjIzNGRmNzllZGJjNTgwOTY3ZGZlMDliNDMyOGM5ZGMuYXBr&iat=1647857532&sig=8f177d06eb281753b03ea79be14efcab&size=122257560&from=cdn&version=latest&x-colo=%40%40%40&x-continent=NA&x-country=US&x-region=CA&x-asn=35916

**Comment by zhongqingsong** [comment]
I guess this is one of the default renaming classes provided, and it is really useful. But sometimes is will destroy the original class name. it means i can't use the search(when is search apk's real class, i find nothing).
So if possible, provide the game's original class name by default. Add a setting to open the auto rename class name. 😊

**Comment by skylot** [comment]
@zhongqingsong
These classes were renamed to make class names correct for recompilation, you can check the reason why class was renamed by comment above that class (enabled on code comments level `INFO` or below):
```
/* renamed from: com.yandex.metrica.impl.ob.pu  reason: case insensitive filesystem */
public final class C1994pu extends Ys implements Zs<IReporter, ReporterConfig> {
```
This class renamed because class with name `Pu` exists in same package and after export these names will collide on case-insensitive file system.
To disable that rename, you can:
1. Disable first or all options in `Rename identifiers` block (below deobfuscation)
2. If your file system is case-sensitive, you can enable that option

About language name: looks like your font don't support Korean symbols, so it doesn't render correctly. Maybe we need to add English names for all languages to make at least that part readable.

**Comment by zhongqingsong** [comment]
> com.yandex.metrica.impl.ob.pu

Thanks, "To fix case sensitivity issues" i got it, and i disabled. It worked.
There a some else doubt, i try to find out other two option, but i didn't find answer,so i'd appreciate any answers：
To make them valid, this is what's mean? It is not work like i thought.
To make printable, I don't understand it at all.
😉

**Comment by skylot** [comment]
@zhongqingsong 
`To make them valid` - will rename all invalid identifiers according to [JLS](https://docs.oracle.com/javase/specs/jls/se18/html/jls-3.html#jls-3.8). For example, identifiers can't start with a number.
`To make printable` - for now, leave only printable ASCII characters (32 to 126 codes), remove others
