### ISSUE TITLE
[Bug] jadx open file diaglog input dir path error

### ISSUE THREAD

**Issue by sornian** [skylot/jadx#1462]
click menu->file->open(ctrl+o)
then i input the dir path ,the dialog is closed instead of get intothis dir
This problem has bothered me for a long time

**Comment by jpstotz** [comment]
I also noticed this behavior. It is caused as the dialog allows to select (multiple) files or a whole directory:
https://github.com/skylot/jadx/blob/1c2b2c072c582195a6a36edd11ba0caa1be16594/jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java#L334

By changing fileSelectionMode to `JFileChooser.FILES_ONLY` it would be possible enter a directory by keyboard so the dialog would change into the specified directory instead of closing. But this would also mean users would no longer be able to select a directory of files.

**Comment by skylot** [comment]
Well, I agree this behavior can be unexpected and sometimes really annoying (accidentally loading a directory with a lot of files can hang up jadx :cry:)
Options are:
1. Just use drag and drop into jadx-gui files pane :rofl:
2. Add separate buttons/actions for files and directories
3. Ask confirmation on directory open (override `approveSelection()` method in `JFileChooser`)
4. Custom file open dialog with separate buttons for files and directories

I like third option, I will check it and also try option 4 with just replacing buttons.

**Comment by skylot** [comment]
Ok, I commit a fix with confirmation on directory loading, hope it will help.
@sornian please check latest [unstable build](https://nightly.link/skylot/jadx/workflows/build/master).
