### ISSUE TITLE
Memory issue using multithreaded decompilation

### ISSUE THREAD

**Issue by Luffitys** [skylot/jadx#1508]
JADX uses a lot more memory per used thread during and after decompilation.

Using 1 thread, jadx consumes this amount of RAM:
![image](https://user-images.githubusercontent.com/51169632/171490933-a0832d44-09f9-4c7a-81fd-5b05207c020f.png)
With just 2 threads, it rises to:
![image](https://user-images.githubusercontent.com/51169632/171491122-df6a5b3b-1f40-4e06-a421-14afbf751a87.png)

Raising the thread count to anything above 2 threads however barely influences the RAM usage.

**Comment by Luffitys** [comment]
Using `Show memory usage bar` the usage spikes from 1.85 GB to 2.8 GB. That's a massive increase. I don't know if there's an issue present, but I'm not sure multithreading should affect it by such an amount.

**Comment by jpstotz** [comment]
Memory usage of Java is very unsteady, it can increase and decrease multiple time while decompiling, that is expected behavior and caused by the Java memory management system and the used garbage collector.
How much memory increase for the second thread is usual I don't know. But this may also depend on the APK and the class size as well as the number of dependencies between the classes.
