### ISSUE TITLE
Decompilation of APK without any code

### ISSUE THREAD

**Issue by DADi590** [skylot/jadx#1534]
Hi. I'm trying to decompile the system FM radio app from my BV9500 phone so that I can understand how it works. Though, when I use your tool, no code comes to the output. I'm attaching a ZIP of the app folder on /system/priv-app (335 KB). Could you fix this please? (Unless I did something wrong? But I just gave the APK to the tool and exported as a Gradle project, to find nothing inside "java" folder - as I was expecting since I see on code on the GUI.)

Thank you.

[FMRadio.zip](https://github.com/skylot/jadx/files/8904236/FMRadio.zip)

**Comment by skylot** [comment]
@DADi590 because this is a system app, it (often) doesn't contain dex file in apk, only vdex/odex/oat files. So you can use tools like [Smali](https://github.com/JesusFreke/smali) or  [vdexExtractor](https://github.com/anestisb/vdexExtractor) to convert these formats to dex and next decompile it with jadx. To save you some time I already did this, check: [FMRadio_fix.apk.zip](https://github.com/skylot/jadx/files/8912104/FMRadio_fix.apk.zip) :slightly_smiling_face:. Anyway, a lot of functions implemented in native lib.

Jadx don't support format like odex or vdex and I don't think will.
Related issues: #285, #167
