### ISSUE TITLE
[core]The recognized class name is wrong, resulting in generated frida and xposed code using the wrong class name

### ISSUE THREAD

**Issue by bhwxha** [skylot/jadx#1578]
link: https://drive.google.com/file/d/13OflkLZUEUXDYqxwujTVCwqEuLy2IRZW/view?usp=sharing
Method Name:**a.a.a.a$c.run()**

The class is **a.a.a.a$c**, but jadx recognizes it as **a.a.a.a**.
This also causes the generated frida code and xposed code to use the wrong class name.

![image](https://user-images.githubusercontent.com/107301547/178942924-6a32b95d-c233-4148-a6fe-7cb7b0fa2726.png)

**Comment by jpstotz** [comment]
Thanks for reporting and for the sample dex file. This a nice and small sample code. May be it is time to set-up some unti-tests to ensure correctness of the different snippets that can be generated.

**Comment by skylot** [comment]
@jpstotz this issue not actually related to frida/xposed snippets, this is an issue in jadx core of incorrect processing of moved/inlined classes (related to #1422), through this method not moved but code incorrectly calculate a class parent (got an additional 'parent'). I commit a fix for that, please check it, because it can bring regressions. And I definitely need more test cases for jadx core API :cry:

**Comment by bhwxha** [comment]
The class name is currently displayed correctly in this location
