### ISSUE TITLE
[feature] Upload jadx-gui to Maven

### ISSUE THREAD

**Issue by NebelNidas** [skylot/jadx#1579]
I'd like to be able to start Jadx's GUI from right within my gradle script (like I do with Enigma [here](https://github.com/NebelNidas/yt-mappings/blob/master/build.gradle#L347-L361=)), and since bundling JARs into git repos is a bit annoying, it would be neat if there was a jadx-gui package on Maven Central :)

**Comment by skylot** [comment]
@NebelNidas this can be hard for jadx-gui because it has dependencies as jar libraries.
I can pack everything into one fat jar, but it will be not very maven friendly, so I don't want to do this.
Also, I don't think anyone else needs this, because this is a very specific case.
Anyway, if you really need this, you can always create your own maven artifact :grin:

**Comment by NebelNidas** [comment]
Providing fat JARs is how these situations are usually handled, but I can see why you wouldn't necessarily like it. I think I'll make a fork and auto-publish that to JitPack 👍
