### ISSUE TITLE
Exporting to HFS+ (macOS) should mind case-insensitivity of the filesystem

### ISSUE THREAD

**Issue by yotams** [skylot/jadx#158]
When exporting a JAR with 2 classes, aA and aa, the first will be exported to "aA.java". Then, jadx will try to export aa to "aa.java". HFS+ is a case insensitive filesystem, so the content of the latter will overwrite the former. I guess this would also be an issue with Windows filesystems (NTFS/FAT).

**Comment by skylot** [comment]
I can add dynamic detection for case insensitive filesystem. Current check work only for Windows and Linux (use [apache common-io library](https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/IOCase.html#SYSTEM))

**Comment by skylot** [comment]
Can anyone check this issue using latest [unstable](https://bintray.com/skylot/jadx/unstable#files) version?
I hope it will work, but I can't test it myself because I don't have a Mac computer

**Comment by sergey-wowwow** [comment]
@skylot 
I use macOS and I didn't meet such errors within last year

**Comment by jpstotz** [comment]
@skylot: I noticed that class renaming is now done automatically. Is there a way to disable this? Because if you don't export the sources you don't need this function. 
Furthermore if you are searching for a specific class by name you won't find it as it has been renamed. This may be unexpected from a user perspective.

**Comment by skylot** [comment]
@jpstotz I see, but now renaming can't be disabled, we need to add the option for that.
And there are many "renaming" types besides deobfuscation:
* to support system case sensitivity
* to make valid java identifiers (to make code compilable)
* to remove not "printable" characters
So this is a good question of how to make this "renaming" option.

@jpstotz do you need the option to disable all such renaming or only some of them?

**Comment by jpstotz** [comment]
@skylot 

From my perspective I don't see a point why someone would like to disable the **renaming because of non-printable characters** - therefore I would assume that this can be always active without problems. 

**Support system case sensitivity** and **make valid Java identifiers** are options you usually only need in case you use the export function (unless you copy parts of the generated Java code via clipboard). Therefore it would be good to have an option for disabling/enabling these two renaming reasons.

**Comment by skylot** [comment]
@jpstotz I open an issue with description for your request: #570
