### ISSUE TITLE
finding reference error

### ISSUE THREAD

**Issue by bhwxha** [skylot/jadx#1591]
link:https://drive.google.com/file/d/1yEzUlBNPa8Jm7H2QozTKfgHM6q47VOuV/view?usp=sharing

Find a reference to class `com.yuanrenxue.match2022.fragment.challenge.ChallengeOneFragment.OooO00o`, the result is empty

![image](https://user-images.githubusercontent.com/107301547/181729053-cd9e4d0d-baf7-4ac3-bb2e-21c65df95ee0.png)

Find reference to the constructor of class `com.yuanrenxue.match2022.fragment.challenge.ChallengeOneFragment.OooO00o`, the result is not empty

![image](https://user-images.githubusercontent.com/107301547/181729375-f6ccb227-424e-4c0b-91f1-ae9f87c8d25e.png)

Also, there is a bug, I'm not sure if it's an optimization or a bug?
Constructor for class `com.yuanrenxue.match2022.fragment.challenge.ChallengeOneFragment.OooO00o`:
The constructor has 2 arguments, but the pseudocode has only 1 argument.

![image](https://user-images.githubusercontent.com/107301547/181731003-573f1cb2-c94a-4dfd-b99e-46caf3e256ff.png)

GDA:

![image](https://user-images.githubusercontent.com/107301547/181731237-22e05019-6722-44f3-a5e4-ac3c92fb9165.png)

**Comment by jpstotz** [comment]
> The constructor has 2 arguments, but the pseudocode has only 1 argument.

That is by design because you have activated to print inner classes inlined like you develop it in Java. Non-static inner classes always have the parent class as first parameter in constructor. In Java code you don't have to write the parent class as parameter, as it is always there, so Jadx does the same if the inner class is shown inlined. 

GDA seems to show the class non-inlined as separate class so the first implicit parameter has to be printed.

**Comment by skylot** [comment]
@bhwxha I fixed the first case (add constructor usages into class usage) and second case is a feature as @jpstotz already mention.
