### ISSUE TITLE
jadx-gui-1.4.3-no-jre-win crash

### ISSUE THREAD

**Issue by JasonYw** [skylot/jadx#1593]
my env 
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)
win11 
when  jadx-gui-1.4.3-no-jre-win search for keyword,jadx will  crash and build a hs_err_pid.log

**Comment by jpstotz** [comment]
If the whole Java runtime crashes and creates an `hs_err_pid.log` then usually this is a problem of the used JRE that we can not fix. 

If you attach the `hs_err_pid.log` to this issue we can check this is caused by something we can change in Jadx or not. IN general I would recommend to use a JRE Java 11+ as there were a lot of improvements in Java 9+ that makes Jadx faster and often more stable.

**Comment by JasonYw** [comment]
I change my jdb version from jdk 8.0 to jdk 11,it crashed angin when I searched some keyword

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Jan S. ***@***.***>
发送时间: Sunday, July 31, 2022 12:56:08 AM
收件人: skylot/jadx ***@***.***>
抄送: rico_wu ***@***.***>; Author ***@***.***>
主题: Re: [skylot/jadx] jadx-gui-1.4.3-no-jre-win crash (Issue #1593)


If the whole Java runtime crashes and creates an hs_err_pid.log then usually this is a problem of the used JRE that we can not fix.

If you attach the hs_err_pid.log to this issue we can check this is caused by something we can change in Jadx or not. IN general I would recommend to use a JRE Java 11+ as there were a lot of improvements in Java 9+ that makes Jadx faster and often more stable.

―
