### ISSUE TITLE
[jadx-gui] Inconsistent search results

### ISSUE THREAD

**Issue by hexpwn** [skylot/jadx#1601]
**Checks before report**

    * checked [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki
    * searched existing issues

**Describe error**

Receiving inconsistent search results. See attached image where `jadx-gui` informs there are 52 results but displays only one.

`grep` returns 58 results in `.smali` files for the same query.

![ss](https://user-images.githubusercontent.com/58829864/182650567-1dbfbb7f-bc92-4666-8387-89bd3ad5b738.png)

**APK used**
`com.amazon.dee.app`

**Comment by skylot** [comment]
@hexpwn jadx trying to undo constant inlining done by compiler, so some string replaced back by `static final` fields. If you disable `Replace constant` option in preferences, you will get that 58 results.
As for incorrectly displayed results, it might be a multithreading issue, because I can't reproduce it, anyway I will try to investigate what cause it :+1:

**Comment by skylot** [comment]
@hexpwn recently I fix several search issues, looks like this issue also fixed. Please check latest unstable build.

**Comment by hexpwn** [comment]
@skylot seems fixed. thank you
