### ISSUE TITLE
Anonymous class already generated

### ISSUE THREAD

**Issue by tamtam22** [skylot/jadx#161]
Hi,

Sometimes the decompiled code looks like:

~~~~
if (Myutils.type_current.equals("app_detail")) {
	publicTools.app_detail_handler.sendMessage(message);
	if (this.down.getDownloadUrl().contains("downloadatoz.com")) {
		/* anonymous class already generated */.start();
	} else {
		/* anonymous class already generated */.start();
	}
	this.current_progress.setText("Invalid");
	this.current_progress.setTextColor(Color.parseColor("#f39801"));
	this.kb.setVisibility(0);
	this.kb.setText("0KB/s");
}
~~~~

Can this comment be replaced with the "generated" class? Thanks

**Comment by asashour** [comment]
Is this still reproducible? I can't find "anonymous class already generated" in Jadx code.

Appreciate providing sample APK or test case.

**Comment by skylot** [comment]
This issue does not appear now, I remove the restriction on only one class inline. Because for now I can't determine if class is anonymous with high confidence. For that I need make full scan of all instructions to collect usage count before decompilation, and this mean to load all code into memory or parse all instructions twice, both are bad solutions.
