### ISSUE TITLE
Jadx android does not convert dex to java

### ISSUE THREAD

**Issue by bassem-saeed** [skylot/jadx#1683]
Whe I tried jadx as a library for Android it converts jar to dex only, but dex to java doesn't work , please fix it

**Comment by skylot** [comment]
@bassem-saeed please share a code you are using, because it is hard to understand what is going wrong.
Also, please check [how to use jadx as a library](https://github.com/skylot/jadx/wiki/Use-jadx-as-a-library) and note that jadx may not work on Android API below 26.

**Comment by bassem-saeed** [comment]
Thanks for you reply,
I work with Kotlin, I converted the java code in the wiki page on GitHub to
Kotlin code.
Like you see I made editText and button,
When I write the DEX file path there is no thing happen, but when I write
the JAR file path the app converts it to dex, so please help me or fix the
problem, and thanks

في الاثنين، ٢٦ سبتمبر ٢٠٢٢ ١١:٤٣ م skylot ***@***.***> كتب:

**Comment by bassem-saeed** [comment]
![Uploading Screenshot_٢٠٢٢٠٩٢٧-١١٢٢٠٣_CodeAssist.jpg…]()

**Comment by bassem-saeed** [comment]
![Screenshot_٢٠٢٢٠٩٢٧-١١٢٢٠٣_CodeAssist](https://user-images.githubusercontent.com/65798784/192607804-a3526c6b-dacd-4383-915e-7661d6e47fa9.jpg)

**Comment by skylot** [comment]
@bassem-saeed it is hard to help because I still don't see any issues, so here some suggestions:
- make sure you include dependency `io.github.skylot:jadx-dex-input` (without it, dex files will be ignored)
- add implementation for `slf4j` logger (something like [slf4j-android](https://github.com/nomis/slf4j-android)) to see errors in logs thrown by jadx.
I suspect jadx can't save files in your output directory (it may not be accessible for your app) so logs should show such errors.

**Comment by jpstotz** [comment]
@bassem-saeed Instead of writing out everything to `/storage/emulated/0` a path which is not directly accessible by apps since Android 11 anymore please use the external app-specific directory you get by [getExternalFilesDir](
https://developer.android.com/reference/android/content/Context#getExternalFilesDir(java.lang.String)).

**Comment by skylot** [comment]
Resolved by author in https://github.com/skylot/jadx/issues/1693#issuecomment-1263700351
