### ISSUE TITLE
[core] method.getInstructions() is null when using jadx as a library

### ISSUE THREAD

**Issue by fa1conn** [skylot/jadx#1727]
I follow the issue #1482 and want to print the instructions of method，but it return null. Other member variables are normal, such as getInsnsCount() could return the count of instructions.

**Comment by jpstotz** [comment]
Have you tried to call `MethodNode.load()`? Afterwards the list of instructions should be initialized.

**Comment by skylot** [comment]
Well, `MethodNode` is considered internal, so better try to not use it. But if you really want to, there are several solutions:
1. Call method `MethodNode.load()` as @jpstotz mentioned
2. As mentioned in # 1482 you can insert additional pass, but in this case you should put in after `ProcessInstructionsVisitor`, so insert line should be:
```java
addCustomPassAfter(passes, ProcessInstructionsVisitor.class, customPass);
```
This will work because instructions array available only in [first passes working on input instructions](https://github.com/skylot/jadx/blob/bb593a84e4286d49d21b53baf849417e5359cc58/jadx-core/src/main/java/jadx/core/Jadx.java#L110-L120), next it replaced with basic blocks tree.

Also, `getInsnsCount()` return an approximation of instructions count, actually it is a size of code block in code units (2 bytes for DEX). Looks like I forget to rename this property after I rename `ICodeReader.getUnitsCount()`.
