### ISSUE TITLE
Question: which Java version needed?

### ISSUE THREAD

**Issue by MdHusainhfz** [skylot/jadx#1764]
As it isn't mentioned readme.md, which java version is recommended/supported for jadx? I got some errors while decompiling with JDK17.

**Comment by jpstotz** [comment]
You can use any Java version in range [8-18] you want. Decompiling errors are usually independent from the used Java version. They are caused by DEX code structures Jadx can not decompile. 

If you upload the apk or jar you are trying to decompile and post the method that can not be decompiled it may be possible to improve Jadx so that it can decompile that method.
