### ISSUE TITLE
[gui] Find usage of public field of interface in all classes

### ISSUE THREAD

**Issue by zzzzfeng** [skylot/jadx#1801]
When I use `find Usage(x)` on a public static field of a interface class, there is no result.
But I do found the field used by other class, and can be redirected to the field by double-click

**Comment by skylot** [comment]
@zzzzfeng please share a sample and class/field name, otherwise I can't reproduce and fix this issue.

**Comment by zzzzfeng** [comment]
Sample jar: [zframework.z.jar.zip](https://github.com/skylot/jadx/files/10985674/zframework.z.jar.zip)  `Just remove the zip extension`

When I set the language to Chinese, it happens. But not for English
![image](https://user-images.githubusercontent.com/8851007/225482247-91e5aacc-f3f1-48a6-b051-b06d1d288d46.png)

**Comment by skylot** [comment]
Oh, I see! This field actually not used in bytecode because it is replaced by compiler to its string value. But during decompilation jadx tries to replace string back to field usage. So as result if you open only `IBundleManager` class you will see 0 usages, but after also opening `BundleManager` new use places will be added from that class, so next time usage list will not be empty.
As workaround for now, you can disable `Replace constants` option in preferences, so strings will be not replaced by fields.
Another workaround is to force decompilation of all classes by searching some not used string to see `complete` results (maybe I should add `Decompile All` button :slightly_smiling_face:)

**Comment by skylot** [comment]
@zzzzfeng I commit a fix. It is not the best solution, but it should resolve the issue.
