### ISSUE TITLE
[core] jadx is does not show lots of classes

### ISSUE THREAD

**Issue by greenozon** [skylot/jadx#1814]
**Checks before report**
- check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki
- search existing issues by exception message

**Describe error**
- jadx shows just a set of all classes inside obfuscated jar, please find the pic below

  **Note**: GitHub don't allow attach files with `.apk` extension, but you can change extension by adding `.zip` at the end :)

example:

![image](https://user-images.githubusercontent.com/765343/230766193-1fbeaca3-a235-4626-a707-24e38034272b.png)

as you see jadx  does not show in left tree classes like aa, ab, etc

**Comment by jpstotz** [comment]
Can you please prove the APK file? Without the APK file it is next to impossible to investigate the problem find why there are differences. In the Jadx tree there is the class `AbstractC0684cj` visible which indicates you have deobfuscation or one of the `Rename" options activated. Are you sure the classes you miss in Jadx have not been renamed because of these options?

Also can you please tell use what is shown on the left side? It looks like a file listing by a JAR file in some ZIP archive tool. If this is the case please describe where the JAR file comes from.

**Comment by greenozon** [comment]
Hm,  you are right
1) this is just a .jar file (but having some obfuscation like aA.class, aa.class present in the same dir
2) are you saying that jadx is doing some automatic renaming so it might come that files which I considered as missed in the left jadx tree pane became auto-renamed?
if yes, are there any options to not do auto-renaming?

3) this is a sample jar that I was showing above... https://www.sendspace.com/file/b4yg3b

**Comment by skylot** [comment]
@greenozon I added new section to how disable class renaming and inline in [Troubleshooting Wiki](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A#some-classes-are-missing):

### Some classes are missing
Jadx can rename or inline classes to make code correct or closer to original. If such changes are not needed, here available options:
- uncheck `Enable deobfuscation` (in jadx-cli disabled by default)
- uncheck all `Rename identifiers` flags (`--rename-flags none` in jadx-cli)
- disable inlining: uncheck `Inline anonymous classes` (`--no-inline-anonymous`), also uncheck `Inline methods` (`--no-inline-methods`)

**Comment by greenozon** [comment]
Thanks a lot!
this is great hint that solved all the raised questions, Ideal job, without any changes in binaries :)

![image](https://user-images.githubusercontent.com/765343/230790017-4777b578-a6cf-42fc-aafd-658bcb8d6cc1.png)


Please feel free to close the ticket
