### ISSUE TITLE
[feature] Provide `plugins/input` as separate library

### ISSUE THREAD

**Issue by NebelNidas** [skylot/jadx#1821]
It would be nice if the contents of [this](https://github.com/skylot/jadx/tree/14a20879d4af353ceca891286c5c47aa9db7df33/jadx-core/src/main/java/jadx/api/plugins/input) directory could be placed into an independent module (`jadx-ir` maybe?) and be provided as its own library.
The reason for this request is that a program I need currently works directly with Java bytecode (through the ASM library), but I want to add support for Dalvik bytecode, too. This involves creating a bytecode abstraction layer, which is quite a lot of work. Looking for already existing solutions, I found [Dex2Jar's intermediate representation module](https://github.com/ThexXTURBOXx/dex2jar/tree/34cdd5e3d597c13c25c05900534e746ab8a8e6e4/dex-ir). Unfortunately though, Dex2Jar is highly out of date and the code quality is quite lacking to say the least. Then I remembered that you added Java support to JADX last year, and for that you already wrote a system lining up quite nicely with my needs. I'll likely need to write my own wrapper around it, but it would save me a lot of time if I could re-use your code here :)

**Comment by skylot** [comment]
@NebelNidas done, name is [`jadx-input-api`](https://github.com/skylot/jadx/tree/895e0f4a2feba9e178417b943782ab6eea648784/jadx-plugins/jadx-input-api).
This is a really nice suggestion to keep this API independent of `jadx-core`, thanks!
But I don't think it can be useful for you, especially for java bytecode input. Because this API is register based and `java-input` plugin uses [awful on-the-fly stack to registers converter](https://github.com/skylot/jadx/blob/d2e6bb236e832ac367398bfbe2f6f4aab57b9050/jadx-plugins/jadx-java-input/src/main/java/jadx/plugins/input/java/data/code/JavaInsnsRegister.java#L30), so it will be really hard to write another java bytecode input.

**Comment by NebelNidas** [comment]
Thanks! In the meantime, a [new JVM ↔ Dalvik bytecode translation library](https://github.com/Col-E/dex-translator) has popped up, which utilizes R8 for most of the heavy lifting, and therefore fulfills my need of having a IR to represent both.
