### ISSUE TITLE
JavaClass.getSourceLine(int) returns null when using jadx as a library

### ISSUE THREAD

**Issue by Lizzo03** [skylot/jadx#1906]
I use jadx as a library, and try to invoke JavaClass.getSourceLine(int). But it returns null. I follow the issue #1482 and #1727, but still have no idea about it. Where should I insert the additional pass?

**Comment by skylot** [comment]
`JavaClass#getSourceLine(int):Integer` return original source line for provided line in decompiled code, and `null` is expected value because of several reasons:
1. debug info is not present in bytecode
2. no source line attached for instructions on provided line
3. jadx lost such info during decompilation
   (can be a bug or decompiled code is changed so much that it is hard to map lines)

Anyway, you can check available lines info map like this:
```java
javaClass.getCodeInfo().getCodeMetadata().getLineMapping()
```

**Comment by Lizzo03** [comment]
Thank you!
