### ISSUE TITLE
[feature]open jadx-gui from double click file or open with

### ISSUE THREAD

**Issue by chaos-cn** [skylot/jadx#1922]
open jadx-gui from double click file or open with

**Comment by jpstotz** [comment]
What is your OS? 

On Windows 10 to my knowledge assigning Jadx-Gui  (EXE version) to APK files or adding it to the list of "Open With" apps works without problems.

**Comment by chaos-cn** [comment]
> What is your OS?
> 
> On Windows 10 to my knowledge assigning Jadx-Gui (EXE version) to APK files or adding it to the list of "Open With" apps works without problems.

MacOS, I use it like [1308](https://github.com/skylot/jadx/issues/1308)

**Comment by skylot** [comment]
@chaos-cn I merged your PR. I added additional checks because it may throw an exception on unsupported platforms (only macOS is supported for that action :rofl:).

Also, I will try to set up [jdeploy](https://www.jdeploy.com/) for next jadx version to provide platform specific installers. Hope it will simplify jadx install. Use #1308 issue to track progress.
