### ISSUE TITLE
Separate output dir for sources and resources

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#204]
Hi, it would be extremely good to change parameter 

>  -d, --output-dir           - output directory

to 

 >  -dr, --output-dir-res           - output directory for resources
 >  -ds, --output-dir-src           - output directory for sources

because currently they are dropped to the same directory. Or I'm missing something and such things already exist? If no, I'd like to implement two behaviours:
1) If none of these parameters is specified, create directories `source` and `res` inside "root"
2) If only one of them is specified, show error and require to specify two of them

**Comment by skylot** [comment]
Ok, but I suggest to not remove -d option and use it as "root" dir for source and res folders if other two not set, also it will be selected from jadx-gui.
And be carefull: jadx has --no-src and --no-res option to skip source or resources output, so you need to require dirs only if they really needed.

**Comment by sergey-wowwow** [comment]
Hi, pr is ready, can you please review?

**Comment by jsentel** [comment]
Get me off this list please and don’t include me in anything else.


Op 15 januari 2018 bij 17:41:00, sergey-wowwow (notifications@github.com)
schreef:

Hi, pr is ready, can you please review?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/skylot/jadx/issues/204#issuecomment-357734247>, or mute
the thread

**Comment by skylot** [comment]
Looks good, but before merge please fix the build
