### ISSUE TITLE
[gui] Code Jumps to incorrect offset in the code area when import statements are enabled

### ISSUE THREAD

**Issue by Ch0pin** [skylot/jadx#2116]
### Issue details

PR: d7ec35791b030771b178b395962171dabfe4b5fb, seems to introduce an issue on the code jump feature. More specifically, when the import statements are enabled:

<img width="532" alt="Screenshot 2024-03-06 at 14 14 01" src="https://github.com/skylot/jadx/assets/4659186/71c3498d-5535-4422-889c-b55de0399a49">

and when the user jumps to a class/method implementation once the jump is taking place correctly and the user is transferred on the right tab and the right offset. 

The problem is taking place when the user revisits a specific node, as he/she will be transferred to a wrong offset in the code area. 

I checked the PRs and up to the one mentioned above, everything seems to work as expected. 

## Steps to reproduce

1. Make sure that you have the import statements enabled
2. Open an APK file, navigate to the manifest and double click on a component (e.g. the main activity)

At this point you will be directed to the correct offset

3. Close the tab and click again on the same component (main activity)

It is expected to jump to a wrong offset in the code area. 

### Jadx version

dev

### Java version

18.0.2.1

### OS

- [ ] Windows
- [ ] Linux
- [X] macOS

**Comment by AndreiKud** [comment]
Sorry for inconvenience. I'll take a look within few days, if @skylot doesn't mind

**Comment by skylot** [comment]
Well, turns out regression was introduced not in PR #2109, but earlier in commit 5c0c1daa71ad4c8b3bfefbbedbd77b44e4f06060.
Adding this line: https://github.com/skylot/jadx/blob/5c0c1daa71ad4c8b3bfefbbedbd77b44e4f06060/jadx-gui/src/main/java/jadx/gui/ui/codearea/CodePanel.java#L63
cause loading of code for other modes tabs (like fallback) and this override jump offset for class. Now offset is taken from fallback code (latest tab) and smaller because fallback don't use imports.

So to fix this issue we need to:
- disable not needed code loading of code mode tabs
- don't process/override offsets for other code modes at all

**Comment by skylot** [comment]
Fixed.
It will be nice if someone verify this fix using [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master) :slightly_smiling_face:

**Comment by Ch0pin** [comment]
@skylot , it seems fixed.  Thank you very much !
