### ISSUE TITLE
`MethodNode#collectArgsWithoutLoading` is a misleading name

### ISSUE THREAD

**Issue by NebelNidas** [skylot/jadx#2142]
I originally added this method two years ago in https://github.com/skylot/jadx/pull/1532, back when I had little understanding of JADX's internals. I'm not quite sure what my line of thought was, but looking at it now it's obvious that this name is wrong, since JADX does indeed load/decompile the method in order to compute the parameters. `collectArgs` would be a more accurate name.

Edit: Also, would it be possible to add a "other" category to the issue templates? Reports like these don't really fit in any of the currently offered options

**Comment by skylot** [comment]
Yeah, it is definitely loading and decompiling :rofl:
Sure, I will rename it to something like `collectArgNodes`, because it returns `VarNode` list.

> Also, would it be possible to add a "other" category to the issue templates?

Turns out people start using such option for everything, so I forbid it.
Also, using more specific categories, asking people to fill required details.
But even with this, people are really good at avoiding such requirements and still not fill these forms :rofl:
So, for now I don't want to allow free form issues.

**Comment by skylot** [comment]
Done.
