### ISSUE TITLE
[feature] Get overriding functions

### ISSUE THREAD

**Issue by ykaridi** [skylot/jadx#2224]
### Describe your idea

given some function is there a way to find all functions that override it?

**Comment by skylot** [comment]
@ykaridi from `MethodNode` you can get `MethodOverrideAttr` like this:
```java
MethodOverrideAttr overrideAttr = mth.get(AType.METHOD_OVERRIDE);
```
Note: pass should be after `OverrideMethodVisitor`

`MethodOverrideAttr` contains this info:
https://github.com/skylot/jadx/blob/a8d889de3da8468d8191e6a0744c9eccb85dd71c/jadx-core/src/main/java/jadx/core/dex/attributes/nodes/MethodOverrideAttr.java#L14-L22

**Comment by ykaridi** [comment]
I actually want this for a ClspMethod :)
And also I want all functions that override this function, and not all functions overriden by it

**Comment by ykaridi** [comment]
For example, lets say I want to find all functions overriding "java.io.Closable->close"

**Comment by ykaridi** [comment]
In addition, would it be possible to rename the ClspMethod and have all overriden methods updated? currently seems buggy whenever ClspMethod is related :)

**Comment by skylot** [comment]
> For example, lets say I want to find all functions overriding "java.io.Closable->close"

You don't really need to use `ClspMethod` it just a info about java classpath.
You can create a `MethodInfo` and use it for search like this:
```java
ClassInfo clsInfo = ClassInfo.fromName(root, "java.io.Closable");
MethodInfo mthInfo = MethodInfo.fromDetails(root, clsInfo, "close", List.of(), ArgType.VOID);
for (ClassNode cls : root.getClasses()) {
	for (MethodNode mth : cls.getMethods()) {
		MethodOverrideAttr overrideAttr = mth.get(AType.METHOD_OVERRIDE);
		if (overrideAttr != null && overrideAttr.getBaseMethods().stream().anyMatch(m -> m.getMethodInfo().equals(mthInfo))) {
			LOG.info("Found: {}", mth);
			mth.rename("newName"); // this rename will also rename all related/overridden methods
		}
	}
}
```
Note that I used `overrideAttr.getBaseMethods()` here because we search for a 'base' method, otherwise you can use `getOverrideList()`.
Also, search above is very inefficient, so if you want to use it often, it is better to prepare some maps to speed it up.

**Comment by ykaridi** [comment]
Thanks!
I think it could be useful to add a default mapper in JADX itself that caches the mapping.

In addition, there seem to be issues regarding overriding "java.lang.Object->equals", "java.lang.Object->hashCode", etc (doesn't seem jadx recognizes this?)

In our example, if I use the UI to rename one method it won't rename all - this seems like a bug, no?

**Comment by skylot** [comment]
> I think it could be useful to add a default mapper in JADX itself that caches the mapping

Jadx already holding too many caches, so I don't want to add a new one until it is really needed.

> In our example, if I use the UI to rename one method it won't rename all - this seems like a bug, no?

Not sure why you may need to rename "java.lang.Object->equals".
Maybe I just exclude methods from `java.lang.Object` to save some memory, because adding these attributes not very useful, and it will be added for too many methods.

**Comment by ykaridi** [comment]
okay thanks :)
