### ISSUE TITLE
[gui] Opening apk with added blank space to its filename lead to crahs

### ISSUE THREAD

**Issue by de-served** [skylot/jadx#2244]
### Issue details

1) Copy filepath & filename with ... terminal? file manager? grab more than needed - with additional space after "filename.apk" so buffer will contain "Drive:\Path\filename.apk "
2) Start jadx-...exe
3) Insert filename from buffer to open file dialog
4) Try to execute "open"

> java.nio.file.InvalidPathException: Trailing char < > at index 80: D:\Projects\Android\e9ac2df792ef.apk 
> 	at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
> 	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
> 	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
> 	at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
> 	at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)

### Jadx version

1.5.0

### Java version

22.0.1, 21.x etc

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by skylot** [comment]
This is not a crash, just provide a correct file path.

**Comment by de-served** [comment]
Maybe just add a trim?
I use Far manager 20+ years
If everyone using it insert filename to commandline with Ctrl-Enter it will add a space at the end awaiting to add any options to commandline.
jadx is the first app for... IDK... 5 years maybe... maybe more... that will react to path with spaces after/before (not inside, of course) as it acts.

**Comment by skylot** [comment]
> Maybe just add a trim?

Done.
@de-served please check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).
In fix, trailing spaces removed only for files opened with file dialog.
This issue is only appearing in Windows. Linux implementation of `File.toPath()` do not check for trailing spaces.
Although, all systems allow having files with trailing spaces.
So jadx now made changes to input paths that can be considered an issue like [this](https://bugs.openjdk.org/browse/JDK-8041694) :rofl:

**Comment by de-served** [comment]
> So jadx now made changes to input paths that can be considered an issue like [this](https://bugs.openjdk.org/browse/JDK-8041694)

Yep... This is crazy enough (when files/dirs have trailing spaces that is hard to observe if it is at the end)
