### ISSUE TITLE
Can I publish

### ISSUE THREAD

**Issue by developer-krushna** [skylot/jadx#2317]
Hello sir can I publish a fully modified version of jadx (for Android api  21)  library  in my account..  Here is my repo https://github.com/developer-krushna/jadx-android-api21

I am waiting for your reply  ..Thank you 🙏

**Comment by skylot** [comment]
Sure, I am not an expert in licensing, but while you mention this origin project in your library it is fine to do any modification and publish/redistribute it.

Also, once you publish, I will mention your library in wiki section ([here](https://github.com/skylot/jadx/wiki/Use-jadx-as-a-library#use-on-android)), because such work is very useful and might be helpful to others.

**Comment by developer-krushna** [comment]
Thank you sir 😍😍😍😍

**Comment by developer-krushna** [comment]
> Sure, I am not an expert in licensing, but while you mention this origin project in your library it is fine to do any modification and publish/redistribute it.
> 
> Also, once you publish, I will mention your library in wiki section ([here](https://github.com/skylot/jadx/wiki/Use-jadx-as-a-library#use-on-android)), because such work is very useful and might be helpful to others.

Now please sir checkout the codes.. I have published a beta version with jar file

https://github.com/developer-krushna/jadx-android-api21

**Comment by skylot** [comment]
> I will mention your library in wiki section ([here](https://github.com/skylot/jadx/wiki/Use-jadx-as-a-library#use-on-android))

Done.
