### ISSUE TITLE
Feature Request: Compare jars 

### ISSUE THREAD

**Issue by fgustovo** [skylot/jadx#260]
decompiling and comparing 2 jar files will be a very nice feature. If its  if its possible you can add this issue to roadmap. 
Thanks.

**Comment by skylot** [comment]
This is nice feature, but I don't think I will implement it. Because you can decompile jars to different folders and use some of many good diff tools for compare these folders. It is not easy to implement such diff ui component and after quick googling I don't find any ready to use solutions. Sorry :(
