### ISSUE TITLE
Activity.findViewById(...) reffers to a missing R class

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#308]
Hi, in smali code in ``` com.ripio.android.activities.RipioWeb ``` I see the following instructions:
```smali
    .line 44
    const v0, 0x7f0b0034

    invoke-virtual {p0, v0}, Lcom/ripio/android/activities/RipioWeb;->setContentView(I)V
```

It means that the constant is hardcoded, but it's decompiled to
```java
    setContentView((int) com.ripio.android.R.layout.activity_webview);
```
nevertheless class ``` com.ripio.android.R ``` is missing (in smali and java code).

APK [com.ripio.android-1.apk.zip](https://github.com/skylot/jadx/files/2170991/com.ripio.android-1.apk.zip)

**Comment by skylot** [comment]
@sergey-wowwow jadx trying to find matching R class in app package (read from manifest), but in this apk such class is missing, there are warning in log:
```
11:28:29 INFO  - Found several 'R' class candidates: [com.google.android.gms.R, com.google.firebase.R, com.google.firebase.firebase_core.R, com.google.firebase.iid.R, com.google.firebase.remoteconfig.R]
11:28:29 WARN  - Unknown 'R' class, create references to 'com.ripio.android.R'
```
So, to produce compilable code jadx must generate R class.
I don't make it yet because R class is generated by standard build process from resources xml files (which jadx restore) and in this case R class will be overwritten.

**Comment by sergey-wowwow** [comment]
@skylot,
Wouldn’t it better to output constants when R class is not found?

**Comment by skylot** [comment]
@sergey-wowwow 
No. Show resources names instead of numbers - jadx main feature which other decompilers don't implement )

**Comment by sergey-wowwow** [comment]
@skylot,
Main feature is quality of generated codes :D

**Comment by sergey-wowwow** [comment]
Hi @skylot,
is that a rule to generate R class in the package directory? Moreover, usually R class is renamed when deobfuscation is enabled. I can implement such feature like I did for ``` public.xml ```, but I'm not sure that it's a correct solution, because referenced field should be already generated in other R class when 
```java
LOG.info("Found several 'R' class candidates: {}", candidates);
```
is logged

**Comment by skylot** [comment]
@sergey-wowwow  I think it is easier and correct to generate R class if not found, because:
- R class can be absent at all
- It is hard to search for obfuscated version (unknown name and package)
- Obfuscated R class can contain renamed fields so it is useless to replace constants with such names

Optionally we can remove obfuscated R classes if we use generated ones instead
