### ISSUE TITLE
how to compile after saving source and resource folders?

### ISSUE THREAD

**Issue by agh620** [skylot/jadx#358]
hello  
i decompiled an apk file by jadx-gui and using "save all (ctrl + s)" for saving source  
now i have 2 folders and edited my source but how can i convert back to apk file?

**Comment by jpstotz** [comment]
IMHO Jadx is the wrong tool for modifying the code of an Android app. Especially because often Jadx can not decompile 100% of the code of an Android app. Usually at least one method can't be decompiled correctly. 

Therefore if you want to modify the code of an app I would suggest to use apktool. However apktool does only decompile the code to Smali which is not as easy to understand as Java. If you only want to do very small modifications you can do that directly in Smali. 

If you still want to give the decompiled code of Jadx a try you need Android Studio. Copy the decompiled code and the resources into a new Android app project. Then try to identify the used libraries and delete the decompiled code of each library (the original library is always better than the decompiled code). Add each identified library as gradle implementation dependency.
