### ISSUE TITLE
Real methods are missing for AsyncTask class, only synthetic

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#397]
Hi. Class ``` p000o.ut ```
```java
public final class ut extends android.os.AsyncTask<android.net.Uri, java.lang.Void, p000o.C1918> {
```
```java
    protected final /* synthetic */ java.lang.Object doInBackground(java.lang.Object[] objArr) {
        return m11367((android.net.Uri[]) objArr);
    }

    protected final /* synthetic */ void onPostExecute(java.lang.Object obj) {
```
and so on. Declarations should be with ``` android.net.Uri ``` type. I checked both ``` master ``` and ``` type-inference-wip ```, but the issue is present everywhere

APK: https://drive.google.com/file/d/1CWN_lmQGz7FCK9qS03gO1vdktHaAgYNn/view?usp=sharing

**Comment by binorelawan** [comment]
hey, did you find solution?

**Comment by sergey-wowwow** [comment]
@skylot 
Can you fix this one too please? It corrupts classes, because method bindings don't match, so it happens that abstract methods are not implemented in non-abstract classes :(

**Comment by skylot** [comment]
@sergey-wowwow I made a fix. 
This issue related to issue #336 (also to #430 and #361). In this case, bridge method renaming was skipped because the target method was direct and private, I don't expect that. So I remove virtual check and made method public. Please check, maybe there are can be other still not covered cases.
