### ISSUE TITLE
Jadx generated invalid statement

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#399]
Hi,
Open ``` com.paypal.android.p2pmobile.navigation.engine.NavigationManager ```, method ``` parseHttpsDeepLink ``` and you will notice code
```java
            if (!android.text.TextUtils.isEmpty(path)) {
                ? r7v4; // <<
                com.paypal.android.p2pmobile.navigation.graph.BaseVertex baseVertex = null;
                if (map != null) {
                    for (? r3v2 : map.keySet()) { // <<
```

APK: https://drive.google.com/file/d/1JcFelgZosEpQc6F3oJFsQF-AxIJNh4r4/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow type inference failed here, thanks for the report!

**Comment by sergey-wowwow** [comment]
@skylot 
Please also check
``` com.paypal.android.p2pmobile.wallet.banksandcards.fragments.EnterCardFragment ```
```java
    private boolean bindStartDateToMutableCredebitCard(@android.support.annotation.NonNull com.paypal.android.foundation.wallet.model.MutableCredebitCard mutableCredebitCard) {
        //...
        ? dateStringParser = new com.paypal.android.p2pmobile.common.utils.DateStringParser( // ...... 
```

APK: https://drive.google.com/open?id=1pdmRyrp6rDEoYsTJn5RLhv39xXRq5Ksh

**Comment by sergey-wowwow** [comment]
@skylot 
May you please fix also this one? There are tons of such invalid generations :(

**Comment by skylot** [comment]
@sergey-wowwow I made a fix for the second case in `type-inference-wip` branch.
And now I am working on other variables declaration issues, I hope I will finish it soon.
Also, there are a lot of issues in `finally` block extraction which can lead to similar problems :(

**Comment by sergey-wowwow** [comment]
@skylot 
Can you please check the same APK, but method ``` com.paypal.android.foundation.instorepay.payment.InStorePayNFCPaymentManagerFactory() ```? It doesn't contain any try-catches, but starts with
```java
    private InStorePayNFCPaymentManagerFactory() {
        ? sqliteEventPersistence2;
```

**Comment by skylot** [comment]
@sergey-wowwow last case also fixed in latest `type-inference-wip` branch.
Short description of changes made in latest commits:
* Additional type inference algorithm which will start only if the first one is failed. It can be time consuming for big methods but must solve most cases. If that algorithm is executed to method will be added comment with result and time: 
```JADX DEBUG: Multi-variable type inference result: success, time: 23 ms```
* Fully redone variable declaration visitor. Known issue: some variables declared at method start instead near variable use.
* Finally extraction also redone: more safe now, don't break CFG. Known issue: sometimes leave some parts of complex expression like empty `if` or loops
