### ISSUE TITLE
type-inference-wip branch: use of unnecessary casts

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#402]
Hi,
class ``` com.paypal.android.foundation.activity.operation.ActivitySummaryListRetrieveOperation ```
```java
    public ActivitySummaryListRetrieveOperation(final com.paypal.android.foundation.activity.model.ActivityFilter activityFilter) {
        this((java.util.List) new java.util.ArrayList<com.paypal.android.foundation.activity.model.ActivityFilter>() {
        });
    }
```
here ``` ArrayList ``` is cast to ``` List ```. It doesn't harm somehow, but isn't that a bug?
APK: https://drive.google.com/file/d/1pdmRyrp6rDEoYsTJn5RLhv39xXRq5Ksh/view?usp=sharing

**Comment by LynxKik** [comment]
Maybe `this` is asking for a List as a param instead of ArrayList?

**Comment by sergey-wowwow** [comment]
@LynxKik 
``` ArrayList ``` is a class implementing interface ``` List ```, that's why I titled it as ``` use of unnecessary casts ```

**Comment by skylot** [comment]
@sergey-wowwow cause of this issue is not very smart way to force compiler select correct overloaded methods. Now jadx just add casts to all arguments if a method is overloaded (exists other methods with same name and arguments count). To fix this issue I need to implement the logic of method selection from arguments like java compiler did.
But in master you don't see such casts because type infered from method calls. So jadx think that result of `new ArrayList()` is `List` and don't and cast because type is equal - this is also not correct :(

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks for your explanation, I got the reason of casts
