### ISSUE TITLE
Inconsistent code error

### ISSUE THREAD

**Issue by cobalt232** [skylot/jadx#42]
Hi. First I would like to say thank you for this great tool. I use it a lot to fix compatibility issues of Android apps running on Blackberry Android Runtime.

The package com.google.android.gsf seems to have some major decompiling problems, especially the following files:

com/google/android/gsf/checkin/CheckinRequestBuilder.java
com/google/android/gsf/checkin/ServiceDumpSys.java

Can you look into this? A fix would be highly appreciated.

File on Mega:
https://mega.co.nz/#!xJUUxCbC!I6iZCpMk8dvCyKT5kBB5XXjZH3LoXF5V9YDUK5u3pWA

**Comment by sergey-wowwow** [comment]
I've found the apk https://www.apkmirror.com/apk/google-inc/google-services-framework/google-services-framework-4-1-2-509230-release/google-services-framework-4-1-2-509230-android-apk-download/
but seems the issue is not reproducible anymore. Some decompile issues exist, but they are already reported individually.
