### ISSUE TITLE
Different generated code for console and gui version

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#430]
Hi, I run jadx with the following arguments
```
jadx.bat --no-replace-consts --show-bad-code --threads-count 4 --deobf --deobf-min 2 --no-imports --output-dir WISH com.contextlogic.wish_2018-12-19.apk
```
and get method in ``` com.contextlogic.wish.activity.BaseFragment ```
```java
    public A getBaseActivity() {
        return (com.contextlogic.wish.activity.BaseActivity) getLifecycleActivity(); // this method is never declared and doesn't exist
    }
```
but gui version with generates correct code
```java
    public A getBaseActivity() {
        return (BaseActivity) getActivity();
    }
```

APK: https://drive.google.com/file/d/1Eit8ZcYI9OTboOnDCA3cil_6E6gkqxN-/view?usp=sharing

**Comment by sergey-wowwow** [comment]
And one more thing in the same class
```java
    public void withActivity(com.contextlogic.wish.activity.BaseFragment.ActivityTask<A> activityTask) {
        com.contextlogic.wish.activity.BaseActivity baseActivity = getBaseActivity(); // returns A
        if (baseActivity != null) {
            activityTask.performTask(baseActivity);
        }
    }
```
shouldn't ``` baseActivity ``` object has ``` A ``` type, but not ``` com.contextlogic.wish.activity.BaseActivity ```? Because if you grep where that method is called, you will see e.g
```java
    class C42772 implements com.contextlogic.wish.activity.BaseFragment.ActivityTask<com.contextlogic.wish.activity.webview.WebViewActivity> {

        public void performTask(com.contextlogic.wish.activity.webview.WebViewActivity webViewActivity) {
            //...
        }
    }
```
so the parameter type is not ``` BaseActivity ```

**Comment by skylot** [comment]
I made a fix. The root of the problem is #336. There I made a rename of method wrapped by the synthetic method to restore its original name in some cases. In this app such renaming was done in method `com.google.android.gms.common.api.internal.zzcc.getLifecycleActivity()`:
```smali
.method public final synthetic getLifecycleActivity()Landroid/app/Activity;
    .locals 1
    invoke-virtual {p0}, Lcom/google/android/gms/common/api/internal/zzcc;->getActivity()Landroid/support/v4/app/FragmentActivity;
    move-result-object v0
    return-object v0
.end method
```
and `zzcc.getActivity()` method  resolved to `android.support.v4.app.Fragment.getActivity()` and this method was renamed to `getLifecycleActivity`.
CLI and GUI  difference occur because of different class processing order, i.e if `zzcc` class not processed then method is not renamed. Order will be same if in GUI you run decompilation without clicking any classes.
In the fix I allow rename only for methods from the same class, I think it is the correct solution. Also, this will be not dependent on class processing order, so there are will be no difference between CLI and GUI.

About different type: you are right there must be `A` type and it must be fixed, but it is not very critical because any `A` type will extends a `BaseActivity` class as declared here:
```java
public abstract class BaseFragment<A extends com.contextlogic.wish.activity.BaseActivity> extends android.support.v4.app.Fragment {
```
so `WebViewActivity` also extends `BaseActivity`.
