### ISSUE TITLE
Incorrect memory usage

### ISSUE THREAD

**Issue by MPeti1** [skylot/jadx#446]
The memory usage indicator on the bottom shows an incorrect amount.

![kep](https://user-images.githubusercontent.com/9215491/52970943-e7a5a300-33b5-11e9-85b2-029ba55850ba.png)

**Comment by jpstotz** [comment]
Incorrect compared to what?

**Comment by jpstotz** [comment]
The memory bar at the bottom shows the Java heap memory usage. For simplicity it is named "memory usage" to avoid confusion as most people don't know what the JVM heap is. Anyway the memory bar's dedication is to display how much more memory is available to the JVM and therefore to see when Jadx is running out of RAM. It is not designed to show the real memory usage of the Jadx process.

The different values you get is most likely caused by the fact that the JVM is "greedy" - it does not release memory once it has allocated it. Only if you are running Java with the G1GC garbage collector RAM can be manually released, however this task can take some seconds and therefore is not performed automatically. You can manually trigger the garbage collector by clicking the memory bar. 

Note that the garbage collector "G1GC" is by default only used by Java on Java 9+. On Java 8 you have to manually enable it using the parameter `-XX:+UseG1GC`.

**Comment by skylot** [comment]
Haha, I knew that somebody will ask about it )))
@MPeti1 this indicator show memory used by the app inside java virtual machine (JVM) and in task manager you see memory used by JVM. And that additional memory was allocated in advance or just recently freed and not yet returned to OS also there some memory used by JVM itself.

**Comment by MPeti1** [comment]
Thanks, now I understand :D
But I think those who are messing with reverse engineering Android apps should know things like what is the Java heap, or at least they should Google it if they don't know
