### ISSUE TITLE
Regenerate R.java file from values/public.xml and values/strings.xml in Android

### ISSUE THREAD

**Issue by riboribo** [skylot/jadx#45]
I'm working on a feature for jadx that would regenerate the gen/R.java file (and modify the other .java files to use 'labels', like R.string.stringName in methods like setText() and getString()) -- from the values/public.xml and values/strings.xml files recovered from Android .apk files.  (I assume that decompiling Android .apk files is a/the principal use of jadx.)

Would this be a feature you'd welcome in jadx?

The (Android) .java files frequently contain statements like:

    setText(R.string.save_exists);    

R.string.save_exists is defined in gen/R.java as:

    public static final class string {
        public static final int save_exists=0x7f050033;
    }

The code jadx reconstructs looks like:

    this.view.setText(2131034163);

The jadx feature would find functions like setText(number,...) and getString(number) and replace the number with 'R.string.save_exists' -- and would append a comment to line containing the text of the string:

    this.view.setText(save_exists);  // String: "A file with the same name already exists" 0x7f05033

This would make it much easier to understand what was going on in decompiled Android code.

**Comment by riboribo** [comment]
Skylot, are you working on this sort of feature?  I see some recent work on loading resources from the resources.asrc file.

**Comment by skylot** [comment]
Sorry, I was very busy last weeks.
 I already implement replacement of resources ids with appropriate resources names, but I don't add comment with values. For find value of some resource in jadx-gui I decode list of all resources with values (open "Resources->*.arsc file"), but it is temporal solution. I will make regeneration of strings.xml and other resources from .arsc file later.
 About regenerate R file: I don't think it is really necessary, because if we replace all ids with names we don't need mapping from R class anymore, also R file will be rewritten if you try to rebuild android project.
