### ISSUE TITLE
smali test structure

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#517]
I guess the test folder structure is not very intuitive.

Currently, there is single package `jadx.tests.smali` which contains only three classes with their smali files, and they are the only invocations of `SmaliTest.getClassNodeFromSmali(String)`.

And most of the smali tests are actually in `jadx.tests.integration` package.

I propose the following:

1. Move all smali java tests to `jadx.integration` package (there is no need for `tests` since we are already in `src/test/java`
2. Introduce `SmaliTest.getClassNode()`, which automatically detects the folder and name of the smali files from the test class full name.
3. Remove `SmaliTest.getClassNodeFromSmaliWithPath` and replace it with `#2`
4. Remove `SmaliTest.getClassNodeFromSmali(String clsName)`; and replace it with `#2`
5. (Possibly) Move the smali files to `src/test/resources/integration`

**Comment by skylot** [comment]
@asashour you are right, I made many tries to figure out how to better work with smali files )
There are some cases need to be supported by "smali test API":
- single smali file - location pattern `testPkg/TestName.smali` (smali class has the same name as a file)
- multiple smali files to reproduce issues requered many classes - all files in `testPkg/TestName/`
- allow test class and smali class have different names (for deobfuscator tests for example)
- allow getting a **list** of `ClassNode` from multiple smali files

So I agree with `#1` and partially with other, because there are no one universal method to support all these cases.
I will try to reduce count of smali methods and move tests from `#1`
