### ISSUE TITLE
question: gui: how best to implement rename

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#524]
This is related to #88, I opened a new issue, in order not to bother the participants.

My current understanding:
- If Deobfuscation is enabled, the "jobf" is used to get all the mapped values.
- If Deobfuscation is disabled, we don't map values.

Questions:
1. Should we support renaming with only Deobfuscation? If no, how we handle "no deobfuscation"
2. If we support it with "jobf", the methods to read/write is in `DeobfPresets` which I guess would need to be public.

**Comment by skylot** [comment]
It is a tough question, I think a lot about it and in any case it will need many steps to implement:
1. All user interactions with jadx must be saved in project level settings (which is not implemented now)
  - additional file will save opened apk, open tabs, open state of left tree view, etc
  - will save all user renaming
  - this will allow to reload internal JadxDecompiler without visible changes. Now enabling deobfuscation closes all tabs and reset tree which is not very usable (same for your exclude package feature)
2. Ideally, I was thinking about injecting additional RenameGuiVisitor which will use user project settings. And now there is no such injection api also, but it will help to implement other nice features.
3. And after all this, we will get very slow renaming implementation, because every rename will decompile all clases again :( To overcome this jadx will need to collect dependencies of all classes and methods and allows to update only one method in class, and we need really close integration of jadx core and gui.

So I am trying to say that RenameVisitor and Deobfuscator do their jobs and  I don't want to alter them heavily.

**Comment by skylot** [comment]
Rename was implemented and merged. Most of suggested parts was also implemented.
