### ISSUE TITLE
gui: project settings

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#526]
This is meant to capture the requirements of having projects settings in the `GUI` module, it is based on the discussion of #524.

Currently, the GUI opens a single API at a time, and I guess this won't change soon. So, accordingly a project is associated with one APK.

What is needed:
1. A way to store the project
2. Projects settings, e.g. APK, open tabs, 'renamed' methods are saved.
3. User can switch between projects (saved internally in Java Preferences)

The main questions are:
1. Should we have an actual file (e.g. with `jadx` extension), or should we store this as we are using Java Preferences for the settings?
2. If a file, what would be the format, XML/Json/custom?
3. When a user changes some setting, should it automatically be saved, or there is `save project` option.

**Update**

Steps:
1. `Recent Files` would be removed, and we would have `Recent Projects`
2. There would be an option to auto-save project settings, or need explicit `Save Project` action
3. <strike>`Exclude` packages feature would be moved from `Preferences` to `Project settings`</strike>
4. The main window title would change from `jadx-gui - name.apk` to `MyProject [full_path_to_MyProject_folder] - jadx-gui` with optional `*` at the beginning when the project is not saved

**Comment by skylot** [comment]
1. I prefer an actual file. I don't like to save tons of settings in Windows registry )) Also opening project will be just opening file, this is simple and intuitive.
2. 'json' is nice and I already use it for 'global' settings
3. This is discussable and there are many scenarios. I think for initial file creation user must explicitly 'save project' and if project already saved in file, we can autosave it on close, or save sometimes on important changes (like new 'rename').

P.S. Now jadx-gui opens only one file at a time because of high memory usage, so several apks might not fit in memory. To overcome this jadx must save decompilation result somehow (this was requested in #444)

Also as requested in #359 jadx will use project file for saving code comment.

**Comment by asashour** [comment]
Question: I updated the original post few times, was a notification sent?

**Comment by jpstotz** [comment]
@asashour I am subscribed to this issue, but I don't receive updates on edits (as far as I know this the common way to handle edits).

**Comment by skylot** [comment]
For me today all notifications from github are delayed like for hours, and some of them are missing. Maybe something wrong with github?

For the update:
Maybe we also leave `Exclude packages` in global settings, because now it is working nice, you don't need exclude same common packages again on every apk.
