### ISSUE TITLE
Issue with apps written on Kotlin.

### ISSUE THREAD

**Issue by redmi111** [skylot/jadx#529]
![image](https://user-images.githubusercontent.com/35992798/55138925-98902200-515a-11e9-91ae-3d121d0a509e.png)
As on the image above decompiled java bytecode of apps written on kotlin doesn't look so good. Hope there'll be a solution for this. 

https://brompwnie.github.io/reversing/2018/02/12/Kotlin-and-Java-How-Hackers-See-Your-Code.html In this link I got some information that the obfuscated kotlin apps doesn't give many junks (like @Metadata before class starts) as compared to non obfuscated apk.  Take a look at it, Thanks.

**Comment by jpstotz** [comment]
I assume you are referring to the way the String fields are initialized: 

`String server1 = new String(new byte[]{(byte)66, (byte) 111, ...});`

**Comment by redmi111** [comment]
Classes not inlined and things like @Metadata' above the class name.

**Comment by jpstotz** [comment]
The @metadata structure is by design not readable for humans, ist is generated by the Kotlin compiler and is used for reflection: 
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-metadata/index.html

**Comment by redmi111** [comment]
[https://brompwnie.github.io/reversing/2018/02/12/Kotlin-and-Java-How-Hackers-See-Your-Code.html](url) can you please refer this link. obfuscation eliminated that. so there might be some workaround to achieve this in jadx decompiler Right?

**Comment by skylot** [comment]
@redmi111 in issues please write what you expect jadx will do.
As I understand you expect:
- `@Metadata` annotation is removed
- All "anonymous" classes are inlined

Anything else?

P.S. Please learn how to insert a link on Github (see [docs](https://guides.github.com/features/mastering-markdown/)), because your links not working (I already fixed them for you)

**Comment by redmi111** [comment]
@skylot thanks for your advice. Yes, you got the point of what I want.

**Comment by skylot** [comment]
@redmi111 ok. But I don't think it will be implemented soon because for general class inlining jadx need to collect usage information for such classes by scanning all code before decompilation. This is not implemented now and it will highly increase decompilation time or memory usage. For remove metadata annotation jadx need check that there is no reflection usage, this is also hard.

**Comment by redmi111** [comment]
Thank you for your reply. No problem.

**Comment by skylot** [comment]
Anonymous class inlining implemented. @Metadata annotation still not removed and don't it is really needed.
