### ISSUE TITLE
ClspGraph to include generic details

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#552]
As communicated in #512, what would be the way to add the generic details to `ClspGraph`?

Appreciate providing sample/pseudo code of the expected entry of one of the methods/classes.

I guess we should start with Collections.

**Comment by skylot** [comment]
At first, I will describe the current `Clsp` concept and implementation:
* Current Java and Android classpath is really big and contains many classes. Jadx needs some information from those classes for correct decompilation (like class hierarchy for type inference) and need to load it at every start, so loading and processing must be really fast. For this jadx store minimum needed information in a binary format close to resulting class structure for minimum conversion.
* Work with binary file (`.jcst`) implemented in `jadx.core.clsp.ClsSet` class, initial conversion from input classpath to binary format  done in `ConvertToClsSet`. Next classes from `ClsSet` added to maps in `ClspGraph`. 
* `ClsSet` stores array of all classes full names and their "parents" (combined array of super class and interfaces), this is enough to build class hierarchy and implement methods like `instanceof` in `ClspGraph`.
* At first I was planning bundle two classpaths (`.jcst` files) for Java and Android. But apparently Android classpath just adds an additional class and core classes are almost the same. So now only Android is bundled. 
* For build `.jcst` file you need to use `ConvertToClsSet` cli tool and as input provide something like `android.jar` from AndroidSDK (this is "stub" jar and all methods are empty).

Next about new features scope:
* generic map for classes and methods
* `throws` list for methods 
* `vararg` info (variable arguments count)
* maybe method access modifiers

To extend the current implementation we need:
* add `ClspGenericMap` class to store a mapping of generics mapping (generic name to `extends` types)
* add `ClspMethod` with fields same as in `MethodInfo` plus reference to `ClspGenericMap` and info about `throws` list and `vararg` (just boolean).

Binary serialization: I prefer manual serialization, it is harder to write but very flexible and efficient. Please note that all saved types just a reference by class id, because we have a full classpath, so there are no external classes.

Also for work with generics, we need some helper class like (`ClspGraph`) which will collect and simplify access to generic information (some sort of api methods). I think we need methods for map generic types to actual types in implementation class. Like for `class A<T>` and `class B extends A<String>` make mapping `T` -> `String` in `A`. These methods will be used in type inference.

**Comment by asashour** [comment]
How was the current `core.jcst` generated?

When I run the following (with latest `Android Studio`)

```
RootNode root = new RootNode(new JadxArgs());
List<InputFile> list = new ArrayList<>();
InputFile.addFilesFrom(Paths.get("C:\\Program Files\\Android\\Android Studio\\plugins\\android\\lib\\android.jar").toFile(),
		list, true);
root.load(list);
set.load(root);
```

There is an error

```
trouble writing output:
com.android.dex.DexIndexOverflowException: Too many method references to fit in one dex file: 95201; max is 65536.
You may try using multi-dex. If multi-dex is enabled then the list of classes for the main dex list is too large.

```

**Comment by skylot** [comment]
You use wrong `android.jar` :)
You need one from Android SDK and path must be like `Android/Sdk/platforms/android-28`. In that dir also must be `android-stubs-src.jar` (the sources for `android.jar`).
Also why you don't use `ConvertToClsSet` as cli tool?

**Comment by asashour** [comment]
Thanks for info.

> Also why you don't use `ConvertToClsSet` as cli tool?

Possibly because I want to see how API works.

I am afraid, using dex to parse the `android.jar` doesn't give sufficient information, as [ProtoId](https://android.googlesource.com/platform/libcore/+/7047230/dex/src/main/java/com/android/dex/ProtoId.java) doesn't give e.g. the generics info.

I will try to use Java Reflection directly on the the jar.

**Comment by skylot** [comment]
> I will try to use Java Reflection directly on the the jar.

Please don't do it.
Try to open `android.jar` with jadx-gui and check the information you need. I think you will find all you need.
Generics and other information are stored differently, mostly in annotations, because it is meta information and needed only for reflection, so it stored separately.
