### ISSUE TITLE
decompiled line for instructions

### ISSUE THREAD

**Issue by artenie** [skylot/jadx#56]
Hello, 

I needed to know the decompiled line for instructions (InsnNode). As the decompiled line was not set for InsnNode, I added the line:

insn.setDecompiledLine(code.getLine());

in jadx.core.codegen.InsnGen, at line 223 (in makeInsn function)

After this, I add insn.getDecompiledLine() to cls.getDecompiledLine() to find the real line in the final code. 

Is this ok to be added to the official repo ?
Or is there a better way of setting the line for instructions ?

Thank you.

**Comment by skylot** [comment]
I think this is ok. I didn't do this because I don't need this information )
Now I only need mapping from decompiled line to source line for show in jadx-gui (see jadx.core.codegen.CodeWriter#getLineMapping).
Actually I don't really understand what are you trying to do, but anyway any contribution are welcome )
