### ISSUE TITLE
Wrong Characters on DexGuarded Classes Names

### ISSUE THREAD

**Issue by enovella** [skylot/jadx#584]
# Problem
![jadx-bug](https://user-images.githubusercontent.com/14809754/55917717-50f0a800-5be8-11e9-853a-0d97e52ef6a2.png)

Also deobfuscation of methods and fields is applied but it wasn't enabled on preferences
```java
package o;

/* renamed from: o.ᴻ */
public final /* synthetic */ class C implements Qn {
    /* renamed from: ˊ */
    private final HttpInterface f19353;
    /* renamed from: ˏ */
    private final DownloadPdfRequest f19354;

    public C(HttpInterface httpInterface, DownloadPdfRequest downloadPdfRequest) {
        this.f19353 = httpInterface;
        this.f19354 = downloadPdfRequest;
    }

    public Object apply(Object obj) {
        return LeagueListingFeature.m29926(this.f19353, this.f19354, (PermissionEnum) obj);
    }
}
```

# Jadx version
Latest unstable

Comments contain the right symbol:
```java
/* renamed from: o.Ч */
public class C extends C {
    /* renamed from: ˋ */
```
 # Sample
- https://apkpure.com/dream11/com.app.dream11Pro/download?from=details
- [Dream11_v3.33.1_apkpure.com.apk.zip](https://github.com/skylot/jadx/files/3066105/Dream11_v3.33.1_apkpure.com.apk.zip)

**Comment by asashour** [comment]
I couldn't understand where are wrong characters, I assume you mean all classes are named `C`.

Well, this happens only in case sensitive systems (e.g. *nix), without enabling deobfuscation. Once you enable deobfuscation, the files are renamed.

In case insensitive systems (e.g. Windows), without deobfuscation, the files are changed to Cxyz.

I guess this is the intended behavior. Please also look into #570, with its pending PR.

Regarding the fields, you are right, I guess they shouldn't be changed, since deobfuscation is disabled.

**Comment by enovella** [comment]
Sorry but i didnt have the time to explain in details. I dont want to enable de-obfuscation because otherwise I cannot reverse the app properly. Having all classes with names `C` is hard.

Will check this pending PR. Thanks!

**Comment by skylot** [comment]
@asashour actually this is a bug. In this case class name have only not "printable" chars so jadx remove them. And as soon as empty name is not correct `C` char was added )) 
But checks for unique names was incorrecly skipped (or it was performed before chars removing).
So this need to be fixed anyway.

**Comment by asashour** [comment]
@enovella Could you test with latest [build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files)? And provide your feedback.

**Comment by enovella** [comment]
Absolutely! Will close the issue after testing it.

**Comment by enovella** [comment]
The testing went well and so many symbols are now displayed. Well done! @skylot @asashour 

However, I encounter some remarks:

**Field names seems odd to me** (de-obfuscation wasn't enabled)
![last](https://user-images.githubusercontent.com/14809754/56099617-3af42780-5f07-11e9-8727-2476439bfeb9.png)

**Still missed characters**
![Screenshot from 2019-04-14 22-41-15](https://user-images.githubusercontent.com/14809754/56099588-c7521a80-5f06-11e9-8735-d098ceca6881.png)

**Comment by enovella** [comment]
Field names are still renamed even with de-obfuscation not marked. This is a bug in my opinion. What do you think guys?

**Comment by asashour** [comment]
It seems now `Rename` options are independent of deobfuscation.

@skylot : should RenameVisitor works only when deobfuscation is enabled?

```
boolean deobfuscationOn = args.isDeobfuscationOn();
if (deobfuscationOn) {
	deobfuscator.execute();
}
checkClasses(root, args);

```

![image](https://user-images.githubusercontent.com/2410127/56117120-b5549400-5f67-11e9-9b2f-da9b13747415.png)

**Comment by skylot** [comment]
@asashour deobfuscation and renaming must work independently.
Deobfuscation renames everything, while "rename" works only when needed.
For complete disable renaming user must uncheck all renaming flags in settings.

@enovella squares are a font issues, you can try change font to one with wider characters support, but anyway this will not fix all squares. Also code editor somehow find font to show any character, but tree view don't.

So here short list of known issues:
* disabling all renaming flags still rename some fields and methods
* code editor can show any chars but tree view can't
* not unique classes names after removing all not "printable" chars (with all renaming flags enabled)

**Comment by enovella** [comment]
Apparently older versions were displaying properly the symbols and field names:
![Screenshot from 2019-04-16 00-57-12](https://user-images.githubusercontent.com/14809754/56172730-b37be680-5fe2-11e9-8402-ed24af754b3d.png)

**Comment by enovella** [comment]
Also, JEB3 handles very well the non-ASCII symbols. How can we do with JADX to do the same?

**Comment by asashour** [comment]
> Also, JEB3 handles very well the non-ASCII symbols. How can we do with JADX to do the same?

I would say: define the requirements :)

**Comment by asashour** [comment]
For the below `codePoint`, it is considered as identifier, although I think it shouldn't. What can be done here?

```
public static void main(String[] args) {
	int codePoint = 65138;
	System.out.println(Character.toChars(codePoint));
	System.out.println(NameMapper.isValidIdentifierPart(codePoint));
	System.out.println(Character.isJavaIdentifierPart(codePoint));
}
```

**Comment by skylot** [comment]
@asashour according to JLS [here](https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.8) java identifier can contain any Unicode characters.
>A "Java letter" is a character for which the method Character.isJavaIdentifierStart(int) returns true. 

And it is funny, definition of language using method from that language :)

**Comment by asashour** [comment]
It seems we should have `RENAME.DISPLAYABLE`, so that we check if [Font.canDisplay](https://docs.oracle.com/javase/8/docs/api/java/awt/Font.html#canDisplay-char-) in the GUI.

**Comment by skylot** [comment]
@asashour `RENAME.DISPLAYABLE`  will not help because:
1. The original intention was to show not modified names, i.e all renaming options disable. And in this case jadx must show any chars.
2. Code viewer already uses `Font.canDisplay` check (internally I guess) and able to find font which can display chars which are not displayable with primary font.
So we need made similar checks in tree viewer or even use code viewer instead of tree labels, like I did in search result.
3. Current "printable" flag superseded this flag because ASCII chars can be shown by any font :))

**Comment by asashour** [comment]
> So here short list of known issues:
> 
> * disabling all renaming flags still rename some fields and methods
> * code editor can show any chars but tree view can't
> * not unique classes names after removing all not "printable" chars (with all renaming flags enabled)

I have to say, I can't reproduce 1. and 2., and don't fully understand the condition of 3.

The screenshot below is of the first question_mark class in package `o`, and it is the same in code view.

![image](https://user-images.githubusercontent.com/2410127/56408504-8303a900-627d-11e9-8bc4-38e44fb7776c.png)

**Comment by enovella** [comment]
Any update for testing? Thanks in advance

**Comment by sergey-wowwow** [comment]
@skylot 
> Current "printable" flag

I see that flag in jadx-gui, but not in the cli version. Has it been added?

**Comment by asashour** [comment]
> I see that flag in jadx-gui, but not in the cli version. Has it been added?

Yes, please check `—rename-flags`

From my humble testing, I see that the font used in both code area and tree doesn’t support all Unicode, we should either try to find another font, or rename non displayed ones.

But I guess there was a hint that there are others issues, but I can’t reproduce.

**Comment by skylot** [comment]
I made a fix which removes difference in chars visibility between tree and code viewer (I use same API as in RSyntaxTextArea [here](https://github.com/bobbylight/RSyntaxTextArea/blob/a13962de37b019cbb4423a472c96dbc0924a69c3/RSyntaxTextArea/src/main/java/org/fife/ui/rtextarea/RTextAreaBase.java#L450)).
And now on my system (Linux) I can view any chars independently which font I selected in preferences. As I understand this is possible because I have installed system fonts which have glyphs for that chars and Linux font subsystem can fallback to them.

@enovella as you have no problems on previous jadx version, you can on latest unstable build try to reset current font to system default by pressing `Reset` button in preferences window. Maybe this helps.

@asashour can you check this change? If it don't help try to reset font or install into your system fonts with wide Unicode support like  [GNU UniFont](https://en.wikipedia.org/wiki/GNU_Unifont), [Noto](https://en.wikipedia.org/wiki/Noto_fonts) or others from list [here](https://en.wikipedia.org/wiki/Unicode_font#List_of_Unicode_fonts) sorted by "Chars"
Also: you can reproduce case of renamed fields with disabled all renaming options by searhing "renamed from" in code

**Comment by asashour** [comment]
1. Well, as a user, Noto seems to be the richest font, however the I couldn't find a Noto font (randomly from the 151) which supports the needed characters.

2. As a user, I am fine with living with strange characters, if I know it is my issue of not having a font with many characters, but I just need to know. I am creating an issue to discuss this.

3. Also, some fonts gives box samples (image below)

4. With disabled all renaming options, and search for "renamed from", there are no renamed fields (image below). From my side, this is an expected behavior.

5. When "printable" is the only selected rename option, fields are renamed (although not fully printable), while classes are not (image below). I am creating an issue to tackle this.

![image](https://user-images.githubusercontent.com/2410127/56626985-4ef50300-6644-11e9-937e-ce9e1b4762a1.png)

![image](https://user-images.githubusercontent.com/2410127/56627686-2b7f8780-6647-11e9-98dc-909fee9ea40a.png)

![image](https://user-images.githubusercontent.com/2410127/56627800-9fba2b00-6647-11e9-93c1-913b35944529.png)

**Comment by enovella** [comment]
Tried another sample with the latest build and the de-obfuscation was automatically triggered without granting it. Also, symbols are not displayed. Any news?

```java
package ᫔;

/* renamed from: ᫔.ࡦ᫔ */
public class C0026 {
    /* renamed from: ᫄ */
    public final byte[] f13;
    /* renamed from: ᫔ */
    public final ZipEntry f14;
```

**Comment by enovella** [comment]
Unmarking the options in the `Rename` window works perfectly. Thanks @skylot!

![Screenshot from 2019-06-07 23-10-17](https://user-images.githubusercontent.com/14809754/59141355-85c77400-8979-11e9-86b8-84329e8e4e47.png)
![Screenshot from 2019-06-07 23-10-40](https://user-images.githubusercontent.com/14809754/59141356-85c77400-8979-11e9-8cb9-e2691df4c9ee.png)
