### ISSUE TITLE
Decompiler logic

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#585]
Regarding the issues we have in e.g. loop/if/while statements.

- Can't we merge some of the logic of different Java decompilers, e.g. FernFlower?
- Was there a base project for the Jadx decompiler, or was it built from scratch? I am asking in case we can merge the updates from the base project.

**Comment by skylot** [comment]
Jadx was written from scratch because at a time I started it (the middle of 2012) there are no open source decompilers (FernFlower source code was closed and project abandoned) as I remember. So I don't even use any ideas from other projects.
And now I think it was a good decision, because if I copy code or ideas from other projects jadx will have same problems and issues, but now if jadx failed to decompile some code you can use other decompiler and there is high possibility that you will find working one.

> Can't we merge some of the logic of different Java decompilers, e.g. FernFlower?

I don't know. I think arhitecture and API will be different so it will be hard. Just fixing issue in jadx is easier I think. Also, as I said, I don't know how other decompilers work ))

**Comment by asashour** [comment]
Great, thanks for info.

**Comment by skylot** [comment]
@asashour if you are interested: [here](https://www.javacodegeeks.com/2013/12/anatomy-of-a-java-decompiler.html) article written by authors of Procyon and CFR decompilers about the anatomy of java decompilers (this is repost, [original](https://www.javaadvent.com/2013/12/anatomy-of-java-decompiler.html) article no longer available).

**Comment by asashour** [comment]
Thanks.

Honestly, I feel a little uncomfortable, that such a nice project, has a single point of `knowledge` :), even though it is an open source.
