### ISSUE TITLE
Invalid casts to wildcard types in children classes

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#662]
Hi, I've noticed tons of invalid assignments, example in ``` com/paypal/merchant/client/features/webview/PPBWebViewActivity.java ```
```java
    public final void qa() {
        this.f18458e.mo1843a(this.f22047g.f20385a.mo26604a().mo43085c((p000.Nya<? super T>) new p000.Yma<java.lang.Object>(this)));
    }
```

Type ``` T ``` is not valid here.
```java
public final /* synthetic */ class Yma implements p000.Nya {
```
```java
public interface Nya<T> {
```
Moreover, class ``` p000.Yma ``` should be declared like this
```java
public final /* synthetic */ class Yma implements p000.Nya<java.lang.Object> {
```

APK: https://drive.google.com/file/d/1LXUNeyqWHv6650M2mhJfg5_HewQQFQXs/view?usp=sharing

**Comment by sergey-wowwow** [comment]
Hi @skylot,
Has it been completely fixed? Because I still see a lot of such errors

**Comment by skylot** [comment]
No, still not fixed, sorry :(
I currently working on this issue but a little stuck, attempts to fix this just broke everything around:
![try](https://user-images.githubusercontent.com/118523/64039230-d1e21900-cb62-11e9-9b5b-ca3b2a450a89.gif)

This issue interferes with overloaded methods and some others code optimizations like unneeded casts removing. Half measures or workarounds did not work, because many tests start failing. I already implement collecting all needed information (generics and overloading flags) from app classes and android classpath, and now trying to figure out how to make correct processing.
I hope I will finish this :+1:

**Comment by sergey-wowwow** [comment]
Cannot be reproduced anymore
