### ISSUE TITLE
Security framework of XStream not initialized

### ISSUE THREAD

**Issue by ftyan805614** [skylot/jadx#681]
E:\软件\apk-tools\jadx-master>gradlew.bat dist

> Configure project :
jadx version: dev

> Task :jadx-gui:createExe FAILED
Security framework of XStream not initialized, XStream is probably vulnerable.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jadx-gui:createExe'.
> net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: Exec failed (1): E:\软件\apk-tools\jadx-master\jadx-gui\build\tmp\launch4j\bin-launch4j-3.12\bin\windres.exe --preprocessor=type -J rc -O coff -F pe-i386 C:\Users\USER\AppData\Local\Temp\launch4j4471193961049524157rc C:\Users\USER\AppData\Local\Temp\launch4j8391365976188188787o

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by jpstotz** [comment]
I assume the problem is caused by your path that contains non-ascii characters: `E:\软件`
On my Windows system Jadx builds without problems using a patch with only ASCII characters.

I also get the warning `Security framework of XStream not initialized, XStream is probably vulnerable.`
This seems to be a known issue of the launch4j-gradle plugin: https://github.com/TheBoegl/gradle-launch4j/issues/82
