### ISSUE TITLE
[core] Incorrect argument type in an implemented method

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#701]
**Checks before report**
- [+] check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) (maybe issue already fixed)
- [+] search existing issues by exception message
 (for example `JadxRuntimeException: Can't find immediate dominator for block`)
- [+] check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki

**Describe error**
Class
```java
/* renamed from: org.apache.commons.a.e.ab */
public class ab<I, O> implements java.io.Serializable, org.apache.commons.p185a.an<I, O> {
```
```java
    /* renamed from: b */
    public O mo21891b(java.lang.Object obj) {
```

Interface
```java
/* renamed from: org.apache.commons.a.an */
public interface an<I, O> {
    /* renamed from: b */
    O mo21891b(I i);
}
```

So the method should be implemented with ``` I ``` type, but not ``` java.lang.Object ```
APK: https://drive.google.com/file/d/1x6VtjwLojBsf2boZlBaDzzSoUdSWkEfU/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow 
Well, I checked your sample and looks like there is no errors in decompiled code, such code is compilable and the same as the original source [here](https://github.com/apache/commons-collections/blob/bf5e45885a2d01010a7b9299feb44c72495fa6d9/src/main/java/org/apache/commons/collections4/functors/InvokerTransformer.java#L127).
Anyway, I add the test to be sure (see [here](https://github.com/skylot/jadx/blob/f57dfb3f2ec4181f2e767b82cdb2e24d1242c8fe/jadx-core/src/test/java/jadx/tests/integration/generics/TestGenericsMthOverride.java#L25)).
I believe java allows such overrides for backward compatibility and because of type erasure, check java specs [here](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.4.2).
