### ISSUE TITLE
[core] Incorrect type variable in generic type

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#702]
**Checks before report**
- [+] check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) (maybe issue already fixed)
- [+] search existing issues by exception message
 (for example `JadxRuntimeException: Can't find immediate dominator for block`)
- [+] check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki

**Describe error**
Original declaration: https://github.com/apache/commons-collections/blob/bf5e45885a2d01010a7b9299feb44c72495fa6d9/src/main/java/org/apache/commons/collections4/comparators/ReverseComparator.java#L39
```java
 private final Comparator<? super E> comparator;
``` 

Decompiled declaration (class ``` org.apache.commons.a.d.g ``` or ``` org.apache.commons.p185a.p497d.C10101g ```)
```java
    private final java.util.Comparator<O> f28238b;
```
but should be also
```java
    private final java.util.Comparator<? super O> f28238b;
```
Because of this bug multiple errors are occurred in the class body

APK: https://drive.google.com/file/d/1x6VtjwLojBsf2boZlBaDzzSoUdSWkEfU/view?usp=sharing

**Comment by sergey-wowwow** [comment]
@skylot 
Can you please fix this one? It prevents resolutions of many methods :(

**Comment by skylot** [comment]
@sergey-wowwow sorry, but I don't see an issue, class `org.apache.commons.a.d.g`:
```java
/* compiled from: TransformingComparator */
public class g<I, O> implements Serializable, Comparator<I> {
    private static final long f21396a = 3456940356043606220L;
    private final Comparator<O> f21397b;
```
is compiled from [TransformingComparator.java](https://github.com/apache/commons-collections/blob/670dc76cf575e1af4a9e8886f07dafd6ee73e2d1/src/main/java/org/apache/commons/collections4/comparators/TransformingComparator.java#L41), because `compiled from` say so and also has same `serialVersionUID` value which is unique. And there field has correct type:
```java
public class TransformingComparator<I, O> implements Comparator<I>, Serializable {
    private static final long serialVersionUID = 3456940356043606220L;
    private final Comparator<O> decorated;
```
So this case looks good to me.

Anyway, can you provide another example of type error in field?

**Comment by sergey-wowwow** [comment]
@skylot 
I actually wanted to ask to fix that bug https://github.com/skylot/jadx/issues/662. But I will review this one too
