### ISSUE TITLE
[core] Use of registers in constructor calls

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#717]
**Checks before report**
- [+] check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) (maybe issue already fixed)
- [+] search existing issues by exception message
- [+] check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki

**Describe error**
Class ``` com.paypal.android.p2pmobile.appconfig.configNode.AtmFinderConfig ```
```java
    public AtmFinderConfig() {
        super(r1, r2, r3, r4, r5, r6);
        Boolean valueOf = Boolean.valueOf(false);
        EciDCSKeys eciDCSKeys = new EciDCSKeys("atmFinder", valueOf);
        EciDCSKeys eciDCSKeys2 = new EciDCSKeys("atmFinderLayout", "map");
        EciDCSKeys eciDCSKeys3 = new EciDCSKeys("atmFinderSearch", "address");
        EciDCSKeys eciDCSKeys4 = new EciDCSKeys("atmFinderShowRecent", valueOf);
        Boolean valueOf2 = Boolean.valueOf(true);
        EciDCSKeys eciDCSKeys5 = new EciDCSKeys("atmFinderShowSearchBar", valueOf2);
        EciDCSKeys eciDCSKeys6 = new EciDCSKeys("atmFinderEnableTabOnMapDisableTabOnList", valueOf2);
    }
```
If a result of execution is used only once, can it be inlined?

APK: https://drive.google.com/file/d/1fCN9PXu8Zw4Kdnhgd0_qmzEvgWLfEU-9/view?usp=sharing

**Comment by skylot** [comment]
> If a result of execution is used only once, can it be inlined?

Jadx usually does this, but with a condition: method invocation order must be preserved. And in this case, it is not possible because of `Boolean.valueOf(true);` method. Anyway, that boolean variables used twice so they will not be inlined. To fix this issue I need to implement "reboxing" to convert `valueOf` call to constants. So it is not a bug fix but a whole new feature :)

P.S. In the previous version of apk (2019-06-20) there is no such issue in this method and this is sad :(

**Comment by skylot** [comment]
I commit initial deboxing implementation. Issue fixed.
But regressions are expected, feel free to report :)
