### ISSUE TITLE
[feature]

### ISSUE THREAD

**Issue by Jose82153** [skylot/jadx#736]
Is there a possibility to export .jar file when deobfuscation is enabled?
I request to be used as lib in my projects.
Thank you.

**Comment by skylot** [comment]
@Jose82153 do you expect that jadx will modify jar and make it deobfuscated?
Sorry, but I will not implement this. Because, I think, there are many tools to do this, like [java-deobfuscator](https://github.com/java-deobfuscator/deobfuscator) and also deobfuscation is not main feature in jadx, it is really simple and lacking many options now.
