### ISSUE TITLE
[core]Decompile an apk, the progress bar has been stuck at 18%

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#741]
Decompile an apk, the progress bar has been stuck at 18%
![2019-08-17_21-13-00](https://user-images.githubusercontent.com/42903751/63212301-be7f8880-c134-11e9-8ca1-4aab0249602b.png)
However, JEB can successfully decompile the apk.
I guess this should be a bug.
This apk download 
 link:https://raw.githubusercontent.com/xmhwws/AApk/master/cool.dingstock.mobile_1.3.4.apk

**Comment by skylot** [comment]
@xmhwws for me latest unstable version not stuck but takes some time to finish (about 1 minute).
The cause if this is a really big method `b.b.cb.g(int, int):int` with 13112 instructions in it. And jadx spend a lot of time in type inference visitor to resolve types of ~2000 variables.
So, for now I am not sure how to speed it up because type inference is hard and not yet finished.
Anyway, thanks for report! I will use your sample for measure performance of type inference :)
