### ISSUE TITLE
Decompilation error, jadx.core.utils.exceptions.JadxOverflowException: Iterative traversal limit reached,

### ISSUE THREAD

**Issue by PavMel** [skylot/jadx#767]
java:
```
java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```
OS:
```
System Version: macOS 10.14.6 (18G103)
Kernel Version: Darwin 18.7.0
```
#### com.finalwire.aidaengine.SysInfo.getSoCModel_ARM()
```
/* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r3v0, resolved type: java.lang.String} */
/*  JADX ERROR: JadxOverflowException in pass: IfRegionVisitor
        jadx.core.utils.exceptions.JadxOverflowException: Iterative traversal limit reached, method: com.finalwire.aidaengine.SysInfo.getSoCModel_ARM():int
        	at jadx.core.utils.ErrorsCounter.addError(ErrorsCounter.java:47)
        	at jadx.core.utils.ErrorsCounter.methodError(ErrorsCounter.java:81)
        */
/* JADX WARNING: Multi-variable type inference failed */
```   
![Screenshot 2019-10-20 at 17 49 12](https://user-images.githubusercontent.com/56612240/67161321-05bb0d00-f362-11e9-9148-2ad66bc04146.png)
[com.finalwire.aida64_165_apps.evozi.com.apk.zip](https://github.com/skylot/jadx/files/3747949/com.finalwire.aida64_165_apps.evozi.com.apk.zip)

**Comment by PavMel** [comment]
Is there any updates? If someone need more info, feel free to ask me about it. I'm not Java programmer and make any changes  by my hands impossible for me.

**Comment by jpstotz** [comment]
@PavMel Even with advanced Java programming skills your ability to make changes would be very very low. The code of Jadx decompiling core is pretty complex and the number of people who know the details of this inner core is very limited. Even I myself have only a basic understanding of this code part.

I have looked at the method but unfortunately I don't think that there will be any progress in near future. The reason is simply, that the referenced method Jadx can't decompile is a huge monster. 
The Jadx instruction dump has more than 11k lines and the code seems to contain multiple nested extremely large case blocks. 

Even increasing the "Iterative traversal limit" does not help here. This method is simply not decompileable by Jadx at the moment.

**Comment by PavMel** [comment]
Hi, @jpstotz, thank you for clarification. So, there is no way for me at this moment?

**Comment by skylot** [comment]
Fixed by increasing iterative limit, and now it is calculated dynamically from blocks count in the method.
Anyway, I am not sure about correctness of the result method code, so be careful.

**Comment by PavMel** [comment]
Method don't decompiled. Got another error:
```
/* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r3v0, resolved type: java.lang.String} */
/* JADX WARNING: Multi-variable type inference failed */
/* Code decompiled incorrectly, please refer to instructions dump. */
```
![Screenshot 2019-10-28 at 03 10 13](https://user-images.githubusercontent.com/56612240/67644219-806ec400-f930-11e9-83b6-179294b49986.png)

**Comment by skylot** [comment]
@PavMel sorry, I forgot to mention this, you need to enable "Show inconsistent code" option in preferences.

**Comment by PavMel** [comment]
Thank you very much. My problem has been solved.
