### ISSUE TITLE
[core]Decompile dex failed

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#774]
I am using the latest version of jadx - jadx-1.0.0-b1162-cf3e17c4.
I came across a very interesting dex file that decompiled against jadx, which can cause jadx to crash. (My computer also has a black screen)
Download link: `https://raw.githubusercontent.com/xmhwws/AApk/master/hook.dex`

**Comment by skylot** [comment]
@xmhwws thanks for share!
Look like this issue in rendering code by `RSyntaxTextArea` component.
Class `cc.binmt.signature.Hook` contains a really big byte array, so `RSyntaxTextArea` just stuck trying to render it. Although I wait for some time and it was able to show code.
So this issue is similar to #654 and looks like jadx really needs to cut long lines of code, but I still not sure how to do that :(

P.S. @xmhwws if you want to view this code you can use CLI version of jadx, and open file in editor which support big files.

**Comment by skylot** [comment]
Fixed in #1266
