### ISSUE TITLE
[core] jadx does not show static enum fields

### ISSUE THREAD

**Issue by addhaloka** [skylot/jadx#830]
```
public enum d implements x.a.c {
    ;
    
    private static x.a.c sB;
}
```
```
.class public final enum Lx/a/d;
.super Ljava/lang/Enum;
.source "SourceFile"

# interfaces
.implements Lx/a/c;
# static fields
.field public static final enum sA:Lx/a/d;

.field private static sB:Lx/a/c;
```
As you can see, sA is dropped

**Comment by addhaloka** [comment]
And, the following smali will be hidden as well
```sget-object v1, Lx/a/d;->sA:Lx/a/d;```
```sput-object v0, Lx/a/d;->sA:Lx/a/d;```

**Comment by skylot** [comment]
@addhaloka can you post full smali for this class or attach original apk? I understand the source of the issue but I need complete class to be sure.

**Comment by addhaloka** [comment]
[case.zip](https://github.com/skylot/jadx/files/4057018/case.zip)

**Comment by skylot** [comment]
@addhaloka 
I made a fix for your case, check the latest unstable build.
Unfortunately, there are lots of not yet supported cases due to code changes by some optimization apps and obfuscators, so not all enums restored. Anyway now jadx will not do partial changes and leave a comment that restore failed.
