### ISSUE TITLE
smali code does not include inner classes of inner classes

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#848]
the lastest unstable jadx(v1.1.0-b1234-c24a3edb)
apk链接：https://drive.google.com/open?id=1Ij0MNPby7Jnd1vnvvjvWXE1MRmttdaXm

class name：`flutter.rhes.top.flutterpluginrdsdk9.SdkHandler`
Search for `success` in java
![image](https://user-images.githubusercontent.com/42903751/74152000-570c4680-4c48-11ea-8330-ecc185a4287a.png)

Search for `success` in smali
![image](https://user-images.githubusercontent.com/42903751/74151701-b584f500-4c47-11ea-8320-d3e9335dea09.png)

**Comment by jpstotz** [comment]
This is not a search problem. The code of the inner class you are searching is just not included in the smali code.

The reason is that the SdkHandler class has inner classes that have inner classes that have inner classes... And currently only the first level of inner classes is included in the smali dump.

I will prepare a pull request that changes this behavior.

**Comment by skylot** [comment]
@jpstotz thanks! I have merged PR.
But just now I realize that jadx can also inline anonymous classes that are not inner to the current class. So, we need somehow get a list of such inlined classes. Maybe an additional class attribute will work.

**Comment by jpstotz** [comment]
@skylot Right, the lambda classes are also displayed inline. 
A list of all inner classes that were included while generating the Java code would be the best option. Then the smali code would really include all relevant classes no matter what setting is active. 

But generating this class list seems to be a little tricky as the outer ´ClassNode´ is not accessible where the actual inlining happens in `InsGen`. Or do you see a different way to get the information on the inlined classes?
