### ISSUE TITLE
[core]String search exception

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#853]
jadx version: the latest unstable build

apk link: https://drive.google.com/open?id=101t04FOij43rKWKiYa4XUITQtfU7rbA1

Search `owned`

in jadx：
![image](https://user-images.githubusercontent.com/42903751/74600270-daef8400-50c9-11ea-9ac4-22d2cb7840be.png)

in jeb：
![image](https://user-images.githubusercontent.com/42903751/74600279-f8245280-50c9-11ea-98aa-029affd5964c.png)

Obviously, `Owned` and `Unowned` were not searched by jadx

**Comment by jpstotz** [comment]
Using the latest unstable release I am getting 9 results when searching for `owned`.
This includes one reference to "Unowned" in `com.digitalchemy.foundation.android.market.h`.

**Comment by xmhwws** [comment]
I was surprised to see your response.
Because I do use the latest version of jadx, I downloaded the source code from github myself and compiled it.
The commit ID is 74b88b4, the latest unstable version.

To rule out my own compilation, I downloaded the version released by skylot: jadx-1.1.0-b1240-74b88b40.zip

But the exception persists:
![image](https://user-images.githubusercontent.com/42903751/74603944-fff8ec80-50f3-11ea-99ae-582d1abdd8a6.png)

Compare the java code:
in jadx：
![image](https://user-images.githubusercontent.com/42903751/74603961-2880e680-50f4-11ea-9151-f6a89f89cf4b.png)

in jeb：
![image](https://user-images.githubusercontent.com/42903751/74603988-62ea8380-50f4-11ea-9c98-a7f1ea1f241a.png)

My jadx configuration is as follows:
![image](https://user-images.githubusercontent.com/42903751/74604001-83b2d900-50f4-11ea-9561-24718a5d4795.png)

**Comment by skylot** [comment]
@xmhwws you disable all rename options so jadx don't change original field names.
`Owned` and other names comes from strings in constructor code, check smali for more detail. To be precise second rename option: "Rename valid" is enable such renaming.
We can discuss if option naming is correct and result is expected.

**Comment by jpstotz** [comment]
The relevant settings seem to be the second rename option ("To be valid identifier"). If this setting is enabled I am getting the expected result:

```
package com.digitalchemy.foundation.android.market;

/* compiled from: src */
public enum h {
    Unknown(0),
    Owned(1),
    Unowned(2);
    

    /* renamed from: a  reason: collision with root package name */
    public final int f3793a;

    private h(int i) {
        this.f3793a = i;
    }
}
```

**Comment by jpstotz** [comment]
@skylot But for an enum it seems to me like this some sort of standard that the first parameter is a String containing it's name. Because otherwise the enum would not have a name at all (which is AFAIK not possible in Java). 
Therefore I would recommend make the enum name recovery independent of the renaming options. I think this also matches the general expectation of the Jadx users.

**Comment by xmhwws** [comment]
Thanks for your reminder, the search is now normal.

I remember why I turned off "To be valid identifier" for the following reasons:
```
/ * renamed from: a reason: collision with root package name * /
public final int f3793a;
```

I want
```
public enum h {
     Unknown (0),
     Owned (1),
     Unowned (2);
     public final int a;
     private h (int i) {
         this.a = i;
     }
}
```
Similar to the java code rendered by jeb, what should I do? What settings are on and off?

**Comment by skylot** [comment]
@xmhwws sorry it is not possible without jadx code changes.
And I am not sure what change must be done, because there are some expectations like:
1. disable all rename options will show original names (#584)
1. resolve collisions with package names (#647) 

Also, I don't want to add many options as it will complicate code and troubleshooting.

@jpstotz in bytecode everything is possible and strings can be worse than original names, so have a switch is a nice option. Also, as soon as it rename enum it is must be a part of renaming block.
