### ISSUE TITLE
[GUI]positioning is incorrect and Ctrl + left mouse button cannot enter the corresponding method

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#861]
jadx version：latest unstable build（v1.1.0-b1243-e444ecb2）
apk link：https://drive.google.com/open?id=1VEF1jTDYip5SSjLELFbFX6b7N5bk2pdx

Problem 1: jadx positioning is incorrect
After decompiling the apk, search for `settings_purchaseInTrialDesc_singular`, double-click the first result with the left mouse button, and jadx is not positioned to the correct position. I need to continue searching in this class to find the correct location.

Problem 2: Ctrl + left mouse button cannot enter the corresponding method
ninja.sesame.app.edge.iab.d.b()
![image](https://user-images.githubusercontent.com/42903751/75088544-b728b400-5589-11ea-9984-4f9d9800c499.png)

**Comment by jpstotz** [comment]
Regarding the wrong positions: It seems like the line index is misplaced because of the multi-line ` /* JADX DEBUG: ` sections added in this class. Internally Jadx seems to count only one line for each of these sections instead of the real line count.

**Comment by xmhwws** [comment]
My mouse pointer stays on the method without any slight offset.
I often encounter this problem using jadx. With the same apk, some methods cannot be clicked into, other methods can be clicked into.
My computer resolution is 1920 * 1080, windows10
![image](https://user-images.githubusercontent.com/42903751/75092346-85c3de80-55b1-11ea-914c-8783f304e38a.png)

**Comment by jpstotz** [comment]
Sorry my fault. By disabling the debug comment `Failed to find minimal casts for resolve` the index was corrected and the method got clickable. Therefore both problems have the same source: the line misplacement.

**Comment by skylot** [comment]
@xmhwws I made a fix. Please check latest unstable build.
The issue was in the incorrect use of OS-specific chars as new lines `\n` [here](https://github.com/skylot/jadx/blob/dea7714ef3207b0f7e0e434d82998dbf20ae7e18/jadx-core/src/main/java/jadx/core/dex/visitors/MethodInvokeVisitor.java#L255-L258) and next counting OS independent `NL` [here](https://github.com/skylot/jadx/blob/7f8d03d1927b95565938a4e2089f4cbed3417979/jadx-core/src/main/java/jadx/core/codegen/CodeWriter.java#L99). As result it was working good on my machine (Linux) but incorrect on Windows.

**Comment by xmhwws** [comment]
thanks
