### ISSUE TITLE
[core] Incorrect decompiling

### ISSUE THREAD

**Issue by amspeople** [skylot/jadx#884]
[classes5.zip](https://github.com/skylot/jadx/files/4333179/classes5.zip)
Use jadx latest unstable.
- class: com.xiaomi.hm.health.bt.device.HMDeviceSource
![image](https://user-images.githubusercontent.com/5773978/76688171-8d6c2580-663b-11ea-9b32-8b1e300abe03.png)
Instead of lines:
`put(Integer.valueOf(HMDeviceSource.a(50, 256)), HMDeviceSource.OTHER_MOZART);
`
Must be code using method **b**, not **a**:
`put(Integer.valueOf(HMDeviceSource.b(50, 256)), HMDeviceSource.OTHER_MOZART);
`

Sample from Luyten:
![image](https://user-images.githubusercontent.com/5773978/76688218-eb990880-663b-11ea-9031-fc7f9522bcc9.png)

**Comment by jpstotz** [comment]
It looks like there the method `HMDeviceSource.a(int,int)` is missing in the Jadx decompiled code. I can see it in the smali code:

```
.method public static synthetic a(II)I
    .registers 2
    .line 1
    invoke-static {p0, p1}, Lcom/xiaomi/hm/health/bt/device/HMDeviceSource;->b(II)I
    move-result p0
    return p0
.end method
```

As you can see this method just calls HMDeviceSource.b(int,int). If this method would exists the code would be equivalent to the code generated by Luyten. I don't know why Luyten does not show this indirection through the `a` method (may be optimized in a way by dex2jar?).

**Comment by amspeople** [comment]
> may be optimized in a way by dex2jar?

Not. I have not used dex2jar. Just pulled the dex file from apk.
Earlier, jadx did "not stumble" on this code. In which version it worked correctly, I no longer remember.

**Comment by jpstotz** [comment]
I tracked it down, the method is not decompiled because it has the flag `synthetic` and is a method of a enum class:
https://github.com/skylot/jadx/blob/master/jadx-core/src/main/java/jadx/core/dex/visitors/EnumVisitor.java#L306

@skylot I am not very familiar with synthetic methods in enum classes but it seems to me like that we can't just hide all synthetic methods. Especially if they are referenced by other code parts.

**Comment by amspeople** [comment]
Thank you so much for responding to my message. I hope @skylot will hear you. And me...

**Comment by skylot** [comment]
@jpstotz You are right! Just removing `isSynthetic` from condition resolve issue and also allow jadx to replace `a` call with `b`. Looks like I made such removing due to possible obfuscation of standard methods, see `TODO` on this method :(

**Comment by jpstotz** [comment]
@skylot Do you remember which type of methods should be removed by the `isSynthetic` check?

And that the current version is not able to hide the obfuscated methods of `valueOf` and `values` is in my opinion not that big problem. When Jadx has to deal with obfuscated code errors are inevitable, we can't foresee all the strange modifications the obfuscators can apply.

**Comment by skylot** [comment]
> Do you remember which type of methods should be removed by the `isSynthetic` check?

I tried to found one yesterday but looks like there are no such methods.

 > And that the current version is not able to hide the obfuscated methods of `valueOf` and `values` is in my opinion not that big problem

Agree, except `values` which uses removed `$VALUES` field, so it must be also removed.
I think it is safe to remove all methods which are uses `$VALUES` field. I will make such a change shortly.

Also looks like `valueOf` it is not safe to remove by name because it can be overriden and have different code. From java doc:
> Note that for a particular enum type T, the implicitly declared `public static T valueOf(String)` method on that enum may be used instead of this method to map from a name to the corresponding enum constant.

**Comment by skylot** [comment]
I made a fix. Hope it doesn't break anything :)
