### ISSUE TITLE
Decompiling more than one obfuscated class at a time

### ISSUE THREAD

**Issue by Rourke101** [skylot/jadx#911]
I am not sure this is an issue or not, but I can't find a manual anywhere.

When I decompile a single obfuscated class, it works just fine. However, when I drop a ZIP/JAR file containing multiple `class` (including the single one that was previously decompiled fine) nothing gets decompiled. The icon for files has changed, so it is like jadx is not detecting anything:

![jad](https://user-images.githubusercontent.com/20154036/79685636-876cf400-823a-11ea-9129-c6ad521a8e39.jpg)

I can see the logs say:
`WARN : No dex files found in ...`
Not sure if this is related:
https://github.com/skylot/jadx/pull/455/files

How can I force decompilation of all classes inside a ZIP file?

**Comment by skylot** [comment]
@Rourke101 looks like conversion jar to dex failed and I can't tell exactly why without a sample.
You can try to convert it yourself using [d8](https://developer.android.com/studio/command-line/d8) from Android SDK.
Or use native java decompiler like [cfr](https://github.com/leibnitz27/cfr) or gui took like [Bytecode Viewer](https://github.com/Konloch/bytecode-viewer)

**Comment by Rourke101** [comment]
mmm.. But this is not a DEX. Can't I decompile files in bulk like they do in single file decompilation?

**Comment by skylot** [comment]
@Rourke101 I think there is some misunderstanding. Jadx **can** load jar files, to do this jar files internally converted to dex, but now jadx uses for such conversion outdated dx library which has limited support for new versions of java classes (see #823). And looks like in your case some classes broke this conversion. So you need manually convert java classes to dex using a new d8 library or just use java native decompiler. 

P.S. For me it is surprising that many people (according to open issues) using jadx to decompile native java bytecode, jadx is obviously bad at it: new java versions not supported, new instructions not supported, it is very slow because of internal conversion, etc... :(

**Comment by Rourke101** [comment]
Thanks for the clarifications. Can you suggest a native decompiler which is **as good as** jadx?

Perhaps I'm using the wrong tool, but it decompiled single classes so well I though I could use it for multiple of them.
