### ISSUE TITLE
support use Android mapping.txt to deobfuscation

### ISSUE THREAD

**Issue by kissazi2** [skylot/jadx#97]
can it support use Android mapping.txt to deobfuscation?
I want to use custom mapping.txt to deobfuscation my source code,but I have no way to do that

**Comment by rpattabi** [comment]
This is very much needed feature for investigating our own apk file generated. For example, we can check whether we correctly did proguard configuration to retain a particular method, yet allowed obfuscation. Since we have mapping.txt with us, deobfuscation will make it much easier for us to verify the code in resulting apk.

If there is such a commandline tool that takes apk and the mapping.txt, it could be easily integrated with jadx. Or may be it is a matter of identifying substitutions from the mapping file. I already see that jadx has a setting to use substituting file name to class name. This feature would be an extension of that.

**Comment by Horaddrim** [comment]
Hey @skylot (or any other maintainer), if you think it's a valid addition to the tool, I can help writing this :smile:

**Comment by Horaddrim** [comment]
I really think it can help in cases such as using a custom dictionary in ProGuard configuration, and you need to debug if your dictionary is not messing up with class names or anything like that. As you may know, obfuscation can be really messy if you go too far on the ProGuard (or any other tool like that) configuration.

**Comment by skylot** [comment]
@Horaddrim sure, this is a nice feature and you can implement it if you want :+1: 
For start you can look at [RenameVisitor](https://github.com/skylot/jadx/blob/c555cd082552c04dbf48e6b62820618c4594df8d/jadx-core/src/main/java/jadx/core/dex/visitors/RenameVisitor.java#L28) and [Deobfuscator](https://github.com/skylot/jadx/blob/c555cd082552c04dbf48e6b62820618c4594df8d/jadx-core/src/main/java/jadx/core/deobf/Deobfuscator.java#L33) classes and make similar parser as currently done at [DeobfPresets](https://github.com/skylot/jadx/blob/c7890f2468a14147d80b151dcac17a7875648fea/jadx-core/src/main/java/jadx/core/deobf/DeobfPresets.java#L22). And feel free to ask any questions :)

**Comment by jpstotz** [comment]
It would be easier to implement this feature request if someone could provide a sample Proguard mapping file and attach it to this issue.

**Comment by skylot** [comment]
@jpstotz I collect some info about Proguard mapping file:
- [Mapping specs and description](https://www.guardsquare.com/en/products/proguard/manual/retrace#Mapping) (scroll to Mapping section)
- [Source code](https://github.com/Guardsquare/proguard/blob/d0e823085ac9a17cb01fa263f15c275c22849edb/base/src/proguard/obfuscate/MappingReader.java#L32) from Proguard for parsing mapping file
- Sample app (just example from Android Studio): [mapping.txt](https://github.com/skylot/jadx/files/4902238/mapping.txt) and [app-release-unsigned.apk.zip](https://github.com/skylot/jadx/files/4902117/app-release-unsigned.apk.zip)


So, looks like parsing is not hard, but it needs some work for integration into jadx to support both mappings format.
Quick TODO list:
- New options in cli and gui: `--deobf-file-format` (`jadx` or `proguard`), `--deobf-file` (for load user file, new menu item in gui)
- Refactor `Deobfuscator` class  to use new interface for save/load mapping file
- Implement that new interface for both formats
- Also this can break `rename` branch as soon it uses `jadx` mapping for renaming

**Comment by nift4** [comment]
Hey everyone, just leaving some hints here because I wished I had some.
I also needed this feature badly while decompiling an massive project. Therefore I started work on an converter that takes mapping.txt and spits out an .jobf file - I was able to make it convert, but then when opening in jadx, I noticed it wasn't able to move classes to other packages (with that proguard configuartion, all obfuscated classes got moved to the default package, and there is no way to undo what with a jobf file). So well, it definitefly needs an jadx patch to allow moving classes around packages with an jobf file but the rest should be doable with an converter like I wrote. Now the need to decompile is gone and I never continued from this point, but if anyone wants to have the converter (that does not work correctly due to the limitation) and is willing to finish it, let me know.

**Comment by skylot** [comment]
> obfuscated classes got moved to the default package, and there is no way to undo that with a jobf file

@nift4 thanks for bringing up this issue!
That should be fixed, but right now I'm not sure how exactly. We can add package in class rename line if original package is empty. But this can interfere with package renames because there is no original package, so this can lead to a lot of changes in deobfuscator code.
I think I will open new issue for this change, because it is not related to 'mapping.txt' issue and also affect jadx-gui.

**Comment by 01Sr** [comment]
@skylot @jpstotz Is any possible add this feature in the future? That is helpful if the feature is integrated.

**Comment by skylot** [comment]
@01Sr work in progress right now. Implementation use [FabricMC/mapping-io](https://github.com/FabricMC/mapping-io) library to support various mapping formats including proguard. Although, proguard is slightly harder because mapping needs to be reversed before apply.

**Comment by Mohammad-Azizi** [comment]
Can you share .jobf structure

**Comment by andrewkuksov** [comment]
@skylot Any progress on that? Or did you postpone it?

**Comment by andrewkuksov** [comment]
@skylot It's great to read this. However, is it possible to do this using the CLI? From what I can see, the `--deobf-cfg-file` option currently supports only JOBF. Should this be done through plugins instead?

**Comment by skylot** [comment]
@andrewkuksov it is `--mappings-path`. Looks like description not updated to actual supported formats.
Anyway, this option may be moved into plugin option in the future, because now some parts already moved :rofl:
And `rename-mappings.format` plugin option description have full list of supported formats :thinking:

**Comment by aa563011992** [comment]
> 是的。看起来描述未更新为实际支持的格式。无论如何，这个选项将来可能会移动到 plugin option 中，因为现在一些部分已经移动🤣了 并且 plugin option description 有完整的支持格式🤔列表`--mappings-path``rename-mappings.format`

Can you provide a complete instruction

**Comment by aa563011992** [comment]
> > 是的。看起来描述未更新为实际支持的格式。无论如何，这个选项将来可能会移动到 plugin option 中，因为现在一些部分已经移动🤣了 并且 plugin option description 有完整的支持格式🤔列表`` --mappings-path``rename-mappings.format ``
> 
> Can you provide a complete instruction

cmd.exe /c D:/Users/56301/Desktop/work_doc/jadx/jadx-1.5.1/bin/jadx D:/Users/56301/Desktop/work_doc/jadx/aabRepertoty/com.vb.valley/app-release.aab -d D:/Users/56301/Desktop/work_doc/jadx/aabRepertoty/com.vb.valley/output --export-gradle --no-res --mappings-path D:/Users/56301/Desktop/work_doc/jadx/aabRepertoty/com.vb.valley/mapping.txt
It didn't work.
